import type { FailureRetryDecision } from "./failure-diagnostic.types";

export const FAILURE_OWNERS = ["REPOSITORY_APPLICATION", "DEPLOYGUARD_PLATFORM", "EXTERNAL_PROVIDER", "UNVERIFIED"] as const;
export type FailureOwner = typeof FAILURE_OWNERS[number];
export const EXTERNAL_PROVIDERS = ["aws", "github", "railpack", "network", "other"] as const;
export type ExternalProvider = typeof EXTERNAL_PROVIDERS[number];

export type FailureContractEntry = {
  owner: Exclude<FailureOwner, "UNVERIFIED">;
  provider: ExternalProvider | null;
  rootCauseCode: string;
  affectedComponent: string;
  summary: string;
  technicalReason: string;
  recommendedAction: string;
  remediationSteps: string[];
  retryDecision: Exclude<FailureRetryDecision, "INSUFFICIENT_EVIDENCE">;
};

const entry = (
  owner: FailureContractEntry["owner"], provider: ExternalProvider | null, rootCauseCode: string,
  affectedComponent: string, summary: string, technicalReason: string, recommendedAction: string,
  retryDecision: FailureContractEntry["retryDecision"], remediationSteps: string[],
): FailureContractEntry => ({ owner, provider, rootCauseCode, affectedComponent, summary, technicalReason, recommendedAction, remediationSteps, retryDecision });

const platform = (code: string, component: string, summary: string, reason: string, action: string, steps: string[]) =>
  entry("DEPLOYGUARD_PLATFORM", null, code, component, summary, reason, action, "NOT_SAFE_YET", steps);
const platformRetry = (code: string, component: string, summary: string, reason: string, action: string, steps: string[]) =>
  entry("DEPLOYGUARD_PLATFORM", null, code, component, summary, reason, action, "SAFE_NOW", steps);
const repository = (code: string, component: string, summary: string, reason: string, action: string, steps: string[]) =>
  entry("REPOSITORY_APPLICATION", null, code, component, summary, reason, action, "SAFE_AFTER_FIX", steps);
const awsBlocked = (code: string, component: string, summary: string, reason: string, action: string, steps: string[]) =>
  entry("EXTERNAL_PROVIDER", "aws", code, component, summary, reason, action, "NOT_SAFE_YET", steps);
const awsRetry = (code: string, component: string, summary: string, reason: string, action: string, steps: string[]) =>
  entry("EXTERNAL_PROVIDER", "aws", code, component, summary, reason, action, "SAFE_NOW", steps);

/**
 * Canonical contract for terminal codes whose code alone proves owner,
 * provider, diagnosis, and recovery. Evidence-dependent umbrella codes are
 * deliberately excluded and classified by FailureDiagnosticService.
 */
export const FAILURE_CONTRACT = {
  DG_DEPLOYMENT_INPUT_REQUIRED: platform("DG_CONFIGURATION_INPUT_REQUIRED", "Service configuration", "Required deployment configuration is missing.", "Requirement admission identified unresolved required input before workflow dispatch.", "Provide the exact missing service-scoped configuration and submit a new deployment.", ["Review the unresolved required inputs.", "Configure them for the affected service.", "Submit deployment admission again."]),
  DG_DEPLOYMENT_REQUIREMENTS_BLOCKED: platform("DG_CONFIGURATION_ADMISSION_BLOCKED", "Service configuration", "Deployment configuration was blocked.", "Requirement admission found a prohibited override, duplicate conflict, or validation blocker.", "Resolve the reported configuration conflict before deploying.", ["Review the persisted admission blockers.", "Correct the affected service configuration.", "Submit deployment admission again."]),
  DG_SERVICE_DIRECTORY_INVALID: platform("DG_SERVICE_DIRECTORY_INVALID", "Service directory contract", "The service directory is invalid.", "The configured repository-relative service path escaped or violated the bounded directory contract.", "Correct the configured service directory before deploying.", ["Review the configured service directory.", "Choose a bounded repository-relative directory.", "Submit a new deployment after correcting the project configuration."]),
  DG_BUILD_TARGET_UNRESOLVED: platform("DG_BUILD_TARGET_UNRESOLVED", "BuildTarget resolution", "DeployGuard could not resolve a canonical BuildTarget.", "Exact-source repository evidence did not produce a complete canonical BuildTarget.", "Resolve the reported BuildTarget admission condition before deploying.", ["Review the persisted BuildTarget evidence.", "Correct the selected service configuration or supported repository topology.", "Submit a new deployment."]),
  DG_BUILD_TARGET_AMBIGUOUS: platform("DG_BUILD_TARGET_AMBIGUOUS", "BuildTarget resolution", "BuildTarget evidence is ambiguous.", "Exact-source topology contains conflicting authoritative BuildTarget evidence.", "Remove the BuildTarget ambiguity before deploying.", ["Review the conflicting topology evidence.", "Make the repository-owned build authority unambiguous.", "Deploy the corrected commit."]),
  DG_BUILD_TARGET_UNSUPPORTED: platform("DG_BUILD_TARGET_UNSUPPORTED", "BuildTarget resolution", "The BuildTarget topology is unsupported.", "The selected exact-source topology is outside the certified BuildTarget contract.", "Use a supported BuildTarget topology before deploying.", ["Review the unsupported topology evidence.", "Select or produce a supported topology.", "Submit a new deployment."]),
  DG_BUILD_TARGET_INVALID: platform("DG_BUILD_TARGET_INVALID", "BuildTarget resolution", "The BuildTarget is invalid.", "A canonical BuildTarget path is missing or escapes the exact repository source.", "Correct the invalid BuildTarget path before deploying.", ["Review the BuildTarget path evidence.", "Correct the repository topology or service selection.", "Deploy the corrected commit."]),
  DG_DEPLOYMENT_CONTRACT_UNSUPPORTED: platform("DG_DEPLOYMENT_CONTRACT_UNSUPPORTED", "Deployment contract", "The repository deployment contract is unsupported.", "Repository-owned package-manager or runtime authority conflicts with the certified deployment contract.", "Correct the repository contract evidence and deploy a new commit.", ["Review the conflicting deployment-contract evidence.", "Make the repository-owned authority deterministic.", "Deploy the corrected commit."]),
  DG_SERVICE_DIRECTORY_MISSING: repository("DG_SERVICE_DIRECTORY_MISSING", "Service directory", "The selected service directory does not exist.", "The selected directory is absent from the admitted immutable source commit.", "Create or select the correct service directory and deploy a new commit.", ["Correct the repository directory or project service selection.", "Commit and push the corrected source.", "Deploy the new immutable commit."]),
  DG_SERVICE_PORT_UNRESOLVED: repository("DG_APPLICATION_PORT_UNRESOLVED", "Application port contract", "The application port could not be resolved.", "Repository evidence did not establish one canonical service port.", "Declare one supported service port and deploy a new commit.", ["Declare the service port in supported repository configuration.", "Commit the change.", "Deploy the new commit."]),
  DG_SERVICE_PORT_CONFLICT: repository("DG_APPLICATION_PORT_CONFLICT", "Application port contract", "Conflicting application ports were declared.", "Repository-owned port evidence disagrees.", "Make the service port declarations consistent and deploy a new commit.", ["Review the reported port sources.", "Choose one canonical port.", "Commit and deploy the correction."]),
  DG_SERVICE_PORT_INVALID: repository("DG_APPLICATION_PORT_INVALID", "Application port contract", "The declared application port is invalid.", "The repository supplied a port outside the supported runtime contract.", "Correct the service port and deploy a new commit.", ["Correct the invalid port declaration.", "Commit the change.", "Deploy the new commit."]),
  DG_APPLICATION_RUNTIME_FAILED: repository("DG_APPLICATION_STARTUP_OR_RUNTIME_FAILED", "Application runtime", "The application did not start or remain healthy.", "Structured application runtime evidence identifies an application-owned failure.", "Correct the application startup/runtime failure and deploy a new commit.", ["Inspect the relevant sanitized runtime evidence.", "Correct the application startup or runtime behavior.", "Deploy the fixed commit."]),
  DG_APPLICATION_EXTERNAL_BINDING_FAILED: repository("DG_APPLICATION_EXTERNAL_BINDING_FAILED", "Application network binding", "The application was not reachable from a separate network peer.", "The immutable application image did not bind to 0.0.0.0 on the platform PORT within the bounded validation period.", "Bind the application to HOST/0.0.0.0 and PORT, then deploy a new commit.", ["Update the application server to bind to 0.0.0.0.", "Consume the platform PORT environment variable.", "Commit and deploy the corrected source."]),
  DG_LOCAL_HOST_PORT_ALLOCATION_FAILED: platformRetry("DG_LOCAL_HOST_PORT_ALLOCATION_FAILED", "Local runtime validation", "DeployGuard could not allocate a local validation port.", "The runner could not allocate or discover the ephemeral host port used for isolated pre-deployment validation.", "Retry after the runner port-allocation condition clears.", ["Verify runner Docker networking is available.", "Retry the same immutable deployment." ]),
  DG_WORKFLOW_CONTRACT_INVALID: platform("DG_WORKFLOW_CONTRACT_INVALID", "DeployGuard workflow contract", "The workflow result contract was incompatible.", "DeployGuard rejected workflow input or terminal evidence that did not match the immutable contract.", "Correct the DeployGuard control-plane/workflow contract before retrying.", ["Verify the pinned workflow release identity.", "Correct the platform contract.", "Retry after the platform fix."]),
  DG_CONTROL_PLANE_VERSION_MISMATCH: platform("DG_CONTROL_PLANE_VERSION_MISMATCH", "DeployGuard control plane", "The backend and reusable workflow versions differ.", "The immutable control-plane compatibility check rejected different commit identities.", "Pin the reusable workflow to the backend control-plane commit.", ["Publish the current control-plane commit.", "Update the reusable workflow pin.", "Restart DeployGuard and submit deployment again."]),
  DG_TERRAFORM_MATERIALIZATION_FAILED: platform("DG_TERRAFORM_MATERIALIZATION_FAILED", "DeployGuard Terraform materialization", "DeployGuard could not materialize the Terraform contract.", "The platform-owned Terraform materialization boundary failed.", "Correct the DeployGuard materialization failure before retrying.", ["Review the bounded materialization evidence.", "Correct the platform condition.", "Retry after the correction."]),
  DG_TERRAFORM_VALIDATE_FAILED: platform("DG_TERRAFORM_VALIDATE_FAILED", "DeployGuard Terraform validation", "Generated Terraform configuration failed validation.", "The platform-owned validation boundary rejected generated configuration.", "Correct the DeployGuard Terraform generation defect before retrying.", ["Review the bounded validation evidence.", "Correct the platform-generated configuration.", "Retry after the correction."]),
  DG_TERRAFORM_PLAN_FAILED: platform("DG_TERRAFORM_PLAN_FAILED", "DeployGuard Terraform plan", "Terraform planning failed at the platform boundary.", "The platform-owned infrastructure contract could not produce an applicable plan.", "Resolve the platform planning condition before retrying.", ["Review the bounded plan evidence.", "Correct the platform condition.", "Retry after the correction."]),
  DG_AWS_RUNTIME_CONFIGURATION_FAILED: platform("DG_AWS_RUNTIME_CONFIGURATION_FAILED", "DeployGuard AWS runtime configuration", "Generated AWS runtime configuration was invalid.", "DeployGuard's platform-owned runtime configuration boundary failed.", "Correct the DeployGuard platform configuration before retrying.", ["Review the bounded runtime-configuration evidence.", "Correct the platform configuration.", "Retry after the correction."]),
  DG_ALB_LISTENER_MISMATCH: platform("DG_ALB_LISTENER_MISMATCH", "Application Load Balancer listener", "The ALB listener does not match the immutable runtime.", "The observed listener identity, protocol, port, or target group conflicts with the admitted runtime topology.", "Reconcile the platform-owned ALB listener before retrying.", ["Review the bounded listener identity evidence.", "Correct the platform topology mismatch.", "Retry after reconciliation."]),
  DG_DATABASE_SECRET_VERSION_MISMATCH: platform("DG_DATABASE_SECRET_VERSION_MISMATCH", "Managed database secret identity", "The managed database secret version does not match the immutable release.", "The Terraform runtime output conflicts with the admitted managed-database secret version.", "Reconcile the platform-owned database secret identity before retrying.", ["Review the immutable database secret-version evidence.", "Restore the expected platform-owned version.", "Retry after reconciliation."]),
  DG_ECS_RELEASE_ONLY_FAILED: platform("DG_ECS_RELEASE_ONLY_FAILED", "ECS release activation", "The release-only ECS activation failed.", "DeployGuard could not safely register or activate the immutable task definition through the release-only contract.", "Resolve the bounded release-activation condition before retrying.", ["Review the release-only failure marker and sanitized evidence.", "Correct the platform or provider condition it identifies.", "Retry only after the condition is resolved."]),
  DG_ECR_CLEANUP_FAILED: awsBlocked("DG_ECR_CLEANUP_FAILED", "Amazon ECR cleanup", "Immutable image repository cleanup failed.", "AWS did not complete or verify deletion of the exact DeployGuard-owned ECR repository.", "Resolve the ECR cleanup condition before retrying Destroy.", ["Review the bounded ECR deletion evidence.", "Restore the required AWS capability or provider availability.", "Retry the failed immutable Destroy operation."]),
  DG_RAILPACK_PREREQUISITE_FAILED: entry("EXTERNAL_PROVIDER", "railpack", "DG_RAILPACK_PROVIDER_PREREQUISITE_FAILED", "Railpack provider", "Railpack prerequisites were unavailable.", "The existing provider boundary identified a Railpack prerequisite failure.", "Retry after Railpack prerequisites are available.", "SAFE_NOW", ["Review provider evidence.", "Retry the operation when the prerequisite is available."]),
  DG_GITHUB_PROVIDER_FAILED: entry("EXTERNAL_PROVIDER", "github", "DG_GITHUB_PROVIDER_OPERATION_FAILED", "GitHub Actions", "GitHub could not accept or execute the operation.", "The existing GitHub provider boundary identified the failure.", "Verify GitHub availability and authorization, then retry.", "SAFE_NOW", ["Review the GitHub provider evidence.", "Restore authorization or wait for provider recovery.", "Retry the operation."]),
  DG_TERRAFORM_APPLY_FAILED: awsBlocked("DG_AWS_TERRAFORM_APPLY_FAILED", "Terraform/AWS infrastructure", "Terraform could not apply the infrastructure change.", "The workflow emitted the authoritative Terraform apply boundary.", "Review the bounded Terraform/AWS evidence and retry only after the provider condition is resolved.", ["Review the relevant Terraform evidence.", "Resolve the reported AWS/provider condition.", "Retry using the existing lifecycle operation."]),
  DG_ECR_PUBLISH_FAILED: awsBlocked("DG_AWS_ECR_PUBLICATION_FAILED", "Amazon ECR", "The deployment image could not be published.", "The workflow emitted the authoritative ECR publication boundary.", "Resolve the AWS/ECR provider condition, then retry.", ["Review ECR provider evidence.", "Restore the required AWS capability.", "Retry the operation."]),
  DG_AWS_AUTHORIZATION_FAILED: awsBlocked("DG_AWS_AUTHORIZATION_FAILED", "AWS authorization", "AWS rejected the deployment authorization.", "The existing AWS provider boundary identified an authorization failure.", "Restore the required AWS authorization before retrying.", ["Review the bounded AWS authorization evidence.", "Restore the required role or policy capability.", "Retry the operation."]),
  DG_AWS_PROVIDER_FAILED: awsRetry("DG_AWS_PROVIDER_FAILED", "AWS provider", "An AWS provider operation failed.", "The existing AWS provider boundary identified the failure.", "Retry after the provider condition is resolved.", ["Review the bounded AWS provider evidence.", "Wait for recovery or correct the provider condition.", "Retry the operation."]),
  DG_RUNTIME_SECRET_MATERIALIZATION_FAILED: awsBlocked("DG_RUNTIME_SECRET_MATERIALIZATION_FAILED", "AWS Secrets Manager runtime configuration", "Runtime secret materialization failed.", "AWS Secrets Manager did not complete DeployGuard's immutable runtime-secret operation.", "Restore AWS Secrets Manager availability and permissions before retrying.", ["Review the bounded runtime-secret failure evidence.", "Verify DeployGuard's AWS Secrets Manager access.", "Retry after the provider condition is corrected."]),
  DG_CLOUD_MAP_REGISTRATION_TIMEOUT: awsRetry("DG_CLOUD_MAP_REGISTRATION_TIMEOUT", "AWS Cloud Map registration", "Managed database service discovery did not converge.", "AWS Cloud Map did not register the current managed-database task identity within the bounded convergence policy.", "Retry the same immutable deployment after Cloud Map converges.", ["Review the bounded Cloud Map evidence.", "Wait for AWS service discovery convergence.", "Retry the failed immutable deployment."]),
  DG_ALB_NOT_ACTIVE: awsRetry("DG_ALB_NOT_ACTIVE", "Application Load Balancer", "The application load balancer did not become active.", "AWS did not report the exact ALB active within the bounded convergence policy.", "Retry the same immutable deployment after the ALB converges.", ["Review the bounded ALB status evidence.", "Wait for AWS ALB convergence.", "Retry the failed immutable deployment."]),
  DG_PUBLIC_DNS_UNRESOLVED: awsRetry("DG_PUBLIC_DNS_UNRESOLVED", "Public DNS", "The public endpoint DNS name did not resolve.", "The exact public ALB hostname did not resolve within the bounded convergence policy.", "Retry the same immutable deployment after DNS converges.", ["Review the bounded DNS evidence.", "Wait for public DNS propagation.", "Retry the failed immutable deployment."]),
  DG_PUBLIC_CONNECTION_FAILED: awsRetry("DG_PUBLIC_CONNECTION_FAILED", "AWS public endpoint connection", "The public endpoint did not accept a connection.", "The public ALB endpoint did not accept a transport connection within the bounded convergence policy.", "Retry the same immutable deployment after the transient connection condition clears.", ["Review the bounded transport and target-health evidence.", "Wait for AWS endpoint convergence.", "Retry the failed immutable deployment."]),
  DG_PUBLIC_REACHABILITY_FAILED: awsRetry("DG_PUBLIC_REACHABILITY_FAILED", "AWS public endpoint reachability", "The public endpoint did not become reachable.", "The ALB continued returning a gateway reachability response after DeployGuard's bounded convergence policy.", "Retry the same immutable deployment after the transient AWS reachability condition clears.", ["Review the bounded public-health and target-health evidence.", "Wait for the AWS public endpoint to converge.", "Retry the failed immutable deployment."]),
  DG_MANAGED_DATABASE_READINESS_FAILED: platform("DG_MANAGED_DATABASE_PLATFORM_READINESS_FAILED", "Managed database readiness", "The managed database did not become ready.", "DeployGuard's platform-owned managed database readiness verification failed.", "Resolve the platform database readiness condition before retrying.", ["Review the managed database readiness evidence.", "Correct the platform condition.", "Retry the deployment."]),
  DG_MANAGED_MYSQL_GRANT_RECONCILIATION_FAILED: platform("DG_MANAGED_MYSQL_GRANT_RECONCILIATION_FAILED", "Managed MySQL account grants", "Managed MySQL grants could not be reconciled.", "DeployGuard's platform-owned MySQL account/grant reconciliation failed.", "Resolve the platform grant reconciliation condition before retrying.", ["Review the bounded MySQL reconciliation evidence.", "Correct the platform condition.", "Retry the deployment."]),
  DG_MANAGED_DATABASE_RECONCILIATION_FAILED: platform("DG_MANAGED_DATABASE_RECONCILIATION_FAILED", "Managed database reconciliation", "Managed database reconciliation blocked deployment.", "DeployGuard rejected the managed database admission state before workflow dispatch.", "Review the managed-database reconciliation evidence before retrying.", ["Review the persisted managed-database reconciliation evidence.", "Resolve the platform-owned condition before deploying again."]),
  DG_RELEASE_FINALIZATION_FAILED: platformRetry("DG_RELEASE_FINALIZATION_FAILED", "DeployGuard release projection", "DeployGuard could not finalize verified release evidence.", "The workflow succeeded, but local release finalization failed.", "Retry finalization through the existing recovery flow.", ["Retain the verified immutable release evidence.", "Retry the failed operation to re-run local finalization."]),
  DG_PROJECT_DELETE_CLEANUP_FAILED: platformRetry("DG_PROJECT_DELETE_CLEANUP_FAILED", "DeployGuard project cleanup", "Verified cloud deletion completed, but local cleanup did not.", "The destroy result was verified before local control-plane cleanup failed.", "Retry local cleanup without redispatching infrastructure deletion.", ["Retain the verified destroy evidence.", "Retry the destroy recovery operation."]),
} as const satisfies Record<string, FailureContractEntry>;

export type AuthoritativeFailureCode = keyof typeof FAILURE_CONTRACT;

export function failureContractFor(code: string): FailureContractEntry | null {
  return Object.prototype.hasOwnProperty.call(FAILURE_CONTRACT, code)
    ? FAILURE_CONTRACT[code as AuthoritativeFailureCode]
    : null;
}
