import { mkdirSync, writeFileSync } from "fs";
import { resolve } from "path";
import { Client } from "pg";

export type CatalogObject = Record<string, unknown>;
export function deterministic(rows: CatalogObject[]) { return rows.sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))); }
const FK = `SELECT 'foreign_key' kind,n.nspname schema,c.relname table_name,k.conname name,array(SELECT a.attname FROM unnest(k.conkey) WITH ORDINALITY q(attnum,ord) JOIN pg_attribute a ON a.attrelid=k.conrelid AND a.attnum=q.attnum ORDER BY q.ord) source_columns,rn.nspname referenced_schema,rc.relname referenced_table,array(SELECT a.attname FROM unnest(k.confkey) WITH ORDINALITY q(attnum,ord) JOIN pg_attribute a ON a.attrelid=k.confrelid AND a.attnum=q.attnum ORDER BY q.ord) referenced_columns,k.confupdtype update_action,k.confdeltype delete_action,k.confmatchtype match_type,k.condeferrable deferrable,k.condeferred initially_deferred,k.convalidated validated,pg_get_constraintdef(k.oid,true) definition FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_class rc ON rc.oid=k.confrelid JOIN pg_namespace rn ON rn.oid=rc.relnamespace WHERE k.contype='f' AND n.nspname='public' AND c.relname<>'migrations'`;
const UQ = `SELECT 'unique_constraint' kind,n.nspname schema,c.relname table_name,k.conname name,array(SELECT a.attname FROM unnest(k.conkey) WITH ORDINALITY q(attnum,ord) JOIN pg_attribute a ON a.attrelid=k.conrelid AND a.attnum=q.attnum ORDER BY q.ord) key_columns,k.condeferrable deferrable,k.condeferred initially_deferred,ci.relname backing_index,pg_get_constraintdef(k.oid,true) definition FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_class ci ON ci.oid=k.conindid WHERE k.contype='u' AND n.nspname='public' AND c.relname<>'migrations'`;
const IDX = `SELECT CASE WHEN i.indisunique THEN 'unique_index' ELSE 'index' END kind,n.nspname schema,c.relname table_name,x.relname name,array(SELECT pg_get_indexdef(i.indexrelid,q.ord,true) FROM generate_series(1,i.indnkeyatts) q(ord)) key_items,i.indnkeyatts key_column_count,array(SELECT a.attname FROM unnest(i.indkey) WITH ORDINALITY q(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum=q.attnum WHERE q.ord>i.indnkeyatts ORDER BY q.ord) included_columns,i.indisunique unique,i.indisprimary primary,i.indisexclusion exclusion,pg_get_expr(i.indpred,i.indrelid,true) predicate,am.amname access_method,i.indisvalid valid,i.indisready ready,k.conname linked_constraint,pg_get_indexdef(i.indexrelid) definition FROM pg_index i JOIN pg_class c ON c.oid=i.indrelid JOIN pg_class x ON x.oid=i.indexrelid JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_am am ON am.oid=x.relam LEFT JOIN pg_constraint k ON k.conindid=i.indexrelid AND k.conrelid=i.indrelid AND k.contype IN ('p','u','x') WHERE n.nspname='public' AND c.relname<>'migrations'`;
async function main(){const database=process.argv[2];if(!database)throw new Error('usage: export-postgres-schema-catalog <database>');const client=new Client({host:process.env.DATABASE_HOST,port:Number(process.env.DATABASE_PORT),user:process.env.DATABASE_USERNAME,password:process.env.DATABASE_PASSWORD,database});await client.connect();const objects=deterministic([...(await client.query(FK)).rows,...(await client.query(UQ)).rows,...(await client.query(IDX)).rows]);await client.end();const output=resolve(process.cwd(),`../docs/architecture/two-lane-migration/evidence/postgres-catalog-${database}.json`);mkdirSync(resolve(output,'..'),{recursive:true});writeFileSync(output,JSON.stringify({database,objects},null,2)+'\n');console.log(`POSTGRES_CATALOG_EXPORT_OK objects=${objects.length} output=${output}`)}
main().catch(e=>{console.error(e);process.exitCode=1});
