import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const root = join(__dirname, "..", "..");
const workflow = readFileSync(join(root, ".github/workflows/deployguard-reusable.yml"), "utf8");
const terraform = readFileSync(join(root, "infrastructure/railpack-runtime/main.tf"), "utf8");
const outputs = readFileSync(join(root, "infrastructure/railpack-runtime/outputs.tf"), "utf8");
const deployment = readFileSync(join(root, "backend/src/projects/railpack-deployment.service.ts"), "utf8");
for (const resource of ["aws_cloudwatch_log_group", "aws_security_group", "aws_lb", "aws_lb_target_group", "aws_lb_listener", "aws_ecs_task_definition", "aws_ecs_service"]) {
  assert.match(terraform, new RegExp(`resource "${resource.replace(/[.*+?^${}()|[\\]\\]/g, "\\$&")}"[\\s\\S]*?for_each\\s+= var\\.services`));
}
assert.match(terraform, /DeployGuardServiceId = each\.key/);
assert.match(terraform, /name\s+= "\/deployguard\/\$\{var\.project_id\}\/services\/\$\{each\.key\}"/);
assert.match(terraform, /security_groups = local\.database_enabled \? \[aws_security_group\.application\[local\.database_service_id\]\.id\] : \[\]/);
assert.match(terraform, /resource "aws_ecs_task_definition" "database"/);
assert.match(terraform, /resource "aws_ecs_service" "database"/);
assert.match(terraform, /resource "aws_service_discovery_private_dns_namespace" "database"/);
const applicationTask = terraform.match(/resource "aws_ecs_task_definition" "application" \{[\s\S]*?\n\}/)?.[0] || "";
assert.doesNotMatch(applicationTask, /name\s*=\s*"database"|aws_efs_file_system\.database/);
assert.match(terraform, /database_runtime[\s\S]*security_groups = local\.database_enabled \? \[aws_security_group\.application\[local\.database_service_id\]\.id\] : \[\]/);
assert.match(terraform, /aws_security_group\.database_efs[\s\S]*aws_security_group\.database_runtime/);
assert.match(outputs, /output "services"/);
assert.match(outputs, /security_group_id/);
assert.match(outputs, /service_port/);
assert.match(outputs, /transport_probe_container_name/);
assert.match(outputs, /platform_health_check_path/);
assert.match(outputs, /cloud_map_service_id/);
assert.match(workflow, /while IFS= read -r service; do[\s\S]*railpack build "\$\{build_env_args\[@\]\}" --name "\$image" "\$build_root"/);
assert.match(workflow, /while IFS= read -r artifact; do[\s\S]*service_port="\$\(jq -r '\.servicePort'[\s\S]*docker run --detach[\s\S]*--env PORT="\$service_port"[\s\S]*--env HOST=0\.0\.0\.0/);
assert.match(workflow, /verify-runtime\.sh[\s\S]*aws-runtime-verification\.json/);
const verifier = readFileSync(join(root, "infrastructure/railpack-runtime/verify-runtime.sh"), "utf8");
for (const fact of ["describe-task-definition", "describe-tasks", "describe-security-groups", "describe-target-groups", "describe-target-health", "filter-log-events", "servicediscovery get-service", "servicediscovery list-instances", "DG_ECS_DIAGNOSTICS"]) assert.match(verifier, new RegExp(fact));
assert.match(verifier, /\.services \| to_entries\[\]/);
assert.match(verifier, /readinessMode:"platform_transport"/);
assert.match(workflow, /terraform -chdir=\.deployguard\/terraform destroy/);
assert.match(workflow, /Select immutable rollback service images/);
assert.doesNotMatch(workflow.match(/Select immutable rollback service images[\s\S]*?Install Terraform/)?.[0] || "", /railpack build/);
assert.match(deployment, /if \(action !== "deploy"\)/, "Rollback and Destroy must consume persisted service revisions before current configuration is read");
console.log("MULTI_SERVICE_RUNTIME=PASS TERRAFORM_FOR_EACH=1 INDEPENDENT_DATABASE=1 ROLLBACK_REBUILD=0 DESTROY_SHARED_STATE=1");
