import "reflect-metadata";
import { strict as assert } from "node:assert";
import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { BuildTargetResolutionError, BuildTargetResolverService } from "../src/projects/build-target-resolver.service";
import { RepositorySourceService } from "../src/projects/repository-source.service";
import { canonicalBuildTarget } from "../src/projects/build-target";

const serviceId = "11111111-1111-4111-8111-111111111111";
const sha = "a".repeat(40);
const resolver = new BuildTargetResolverService();
const write = async (root: string, path: string, value: string) => { await mkdir(join(root, path, ".."), { recursive: true }); await writeFile(join(root, path), value); };
const packageJson = (name: string, dependencies: Record<string, string> = {}) => JSON.stringify({ name, version: "1.0.0", scripts: { build: "node build.js", start: "node index.js" }, dependencies });
const resolve = (root: string, serviceDirectory: string, override?: unknown) => resolver.resolve(root, { serviceId, sourceSha: sha, serviceDirectory, override });

void (async () => {
  const root = await mkdtemp(join(tmpdir(), "deployguard-build-target-"));
  try {
    // Standalone manager authority remains service-scoped and never creates workspace commands.
    for (const [lockfile, manager] of [["package-lock.json", "npm"], ["pnpm-lock.yaml", "pnpm"], ["yarn.lock", "yarn"], ["bun.lockb", "bun"]] as const) {
      const fixture = join(root, lockfile.replace(/\W/g, "_")); await mkdir(fixture); await write(fixture, "package.json", packageJson(`standalone-${lockfile}`)); await write(fixture, lockfile, "lock");
      const target = await resolve(fixture, "."); assert.equal(target.strategy, "isolated"); assert.equal(target.contract, "JS_STANDALONE"); assert.equal(target.serviceDirectory, "."); assert.equal(target.buildRoot, "."); assert.equal(target.installRoot, "."); assert.deepEqual(target.execution, { packageTarget: null, packageManager: manager, buildCommand: null, startCommand: null });
    }
    const declaredOnly = join(root, "declared-manager-only"); await mkdir(declaredOnly); await write(declaredOnly, "package.json", JSON.stringify({ ...JSON.parse(packageJson("declared-manager-only")), packageManager: "yarn@4.6.0" })); assert.equal((await resolve(declaredOnly, ".")).execution.packageManager, "yarn", "a standalone packageManager declaration is authoritative without a lockfile");
    const matchingManager = join(root, "matching-manager"); await mkdir(matchingManager); await write(matchingManager, "package.json", JSON.stringify({ ...JSON.parse(packageJson("matching-manager")), packageManager: "npm@10.0.0" })); await write(matchingManager, "package-lock.json", "{}"); const matchingTarget = await resolve(matchingManager, "."); assert.equal(matchingTarget.execution.packageManager, "npm", "matching declaration and lockfile reconcile to npm"); const { fingerprint: _matchingFingerprint, ...unsealedMatchingTarget } = matchingTarget; const changedManager = canonicalBuildTarget({ ...unsealedMatchingTarget, execution: { ...matchingTarget.execution, packageManager: "pnpm" } }); assert.notEqual(changedManager.fingerprint, matchingTarget.fingerprint, "standalone manager authority is immutable BuildTarget fingerprint evidence");
    const standaloneConflict = join(root, "standalone-manager-conflict"); await mkdir(standaloneConflict); await write(standaloneConflict, "package.json", JSON.stringify({ ...JSON.parse(packageJson("standalone-manager-conflict")), packageManager: "npm@10.0.0" })); await write(standaloneConflict, "pnpm-lock.yaml", "lockfileVersion: '9.0'\n"); await assert.rejects(() => resolve(standaloneConflict, "."), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED", "conflicting standalone packageManager and lockfile block admission");
    const standaloneLocksConflict = join(root, "standalone-locks-conflict"); await mkdir(standaloneLocksConflict); await write(standaloneLocksConflict, "package.json", packageJson("standalone-locks-conflict")); await write(standaloneLocksConflict, "package-lock.json", "{}"); await write(standaloneLocksConflict, "pnpm-lock.yaml", "lockfileVersion: '9.0'\n"); await assert.rejects(() => resolve(standaloneLocksConflict, "."), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED", "multiple standalone lockfile authorities block admission");
    const pnpm = join(root, "pnpm-shared"); await mkdir(pnpm); await write(pnpm, "pnpm-workspace.yaml", "packages:\n  - packages/*\n"); await write(pnpm, "pnpm-lock.yaml", "lockfileVersion: '9.0'\n"); await write(pnpm, "packages/client/package.json", packageJson("@fixture/client")); await write(pnpm, "packages/client/src/index.ts", "export {}\n"); await write(pnpm, "packages/shared/package.json", packageJson("@fixture/shared"));
    const clientTarget = await resolve(pnpm, "packages/client"); assert.equal(clientTarget.workspaceRoot, "."); assert.equal(clientTarget.buildRoot, "."); assert.equal(clientTarget.installRoot, "."); assert.equal(clientTarget.strategy, "workspace"); assert.equal(clientTarget.contract, "JS_WORKSPACE_MEMBER"); assert.equal(clientTarget.packageIdentity, "@fixture/client"); assert.deepEqual(clientTarget.execution, { packageTarget: "@fixture/client", packageManager: "pnpm", buildCommand: "pnpm --filter @fixture/client run build", startCommand: "pnpm --filter @fixture/client run start" }); assert.deepEqual(clientTarget.dependencyPaths, []);
    const again = await resolve(pnpm, "packages/client"); assert.equal(clientTarget.fingerprint, again.fingerprint, "same SHA and topology are deterministic");
    const { fingerprint: _fingerprint, ...unsealedClientTarget } = clientTarget;
    const changedExecution = canonicalBuildTarget({ ...unsealedClientTarget, execution: { ...clientTarget.execution, startCommand: "pnpm --filter @fixture/client run start:alternate" } });
    assert.notEqual(changedExecution.fingerprint, clientTarget.fingerprint, "package-target execution commands are immutable BuildTarget fingerprint facts");
    await write(pnpm, "README.md", "irrelevant"); assert.equal((await resolve(pnpm, "packages/client")).fingerprint, clientTarget.fingerprint, "irrelevant content cannot alter ownership");
    await write(pnpm, "pnpm-workspace.yaml", "packages:\n  - packages/*\n  - tools/*\n"); assert.notEqual((await resolve(pnpm, "packages/client")).fingerprint, clientTarget.fingerprint, "changed workspace topology changes the fingerprint"); await write(pnpm, "pnpm-workspace.yaml", "packages:\n  - packages/*\n");
    assert.equal(clientTarget.serviceDirectory, "packages/client", "selected runnable package identity remains distinct from the workspace root and unselected siblings");

    const rootApplication = join(root, "root-application"); await mkdir(rootApplication); await write(rootApplication, "package.json", JSON.stringify({ ...JSON.parse(packageJson("root-app")), private: true, packageManager: "pnpm@10.0.0", workspaces: ["packages/*"] })); await write(rootApplication, "pnpm-workspace.yaml", "packages:\n  - packages/*\n"); await write(rootApplication, "pnpm-lock.yaml", "lockfileVersion: '9.0'\n"); await write(rootApplication, "packages/library/package.json", packageJson("library"));
    const rootTarget = await resolve(rootApplication, "."); assert.equal(rootTarget.contract, "JS_WORKSPACE_MEMBER"); assert.equal(rootTarget.workspaceRoot, "."); assert.equal(rootTarget.execution.packageTarget, "root-app", "a named root package is a valid workspace execution target");
    const glob = join(root, "glob"); await mkdir(glob); await write(glob, "pnpm-workspace.yaml", "packages:\n  - packages/**\n  - '!packages/excluded/**'\n"); await write(glob, "pnpm-lock.yaml", "lockfileVersion: '9.0'\n"); await write(glob, "packages/nested/app/package.json", packageJson("nested-app")); await write(glob, "packages/excluded/app/package.json", packageJson("excluded-app"));
    assert.equal((await resolve(glob, "packages/nested/app")).contract, "JS_WORKSPACE_MEMBER", "** includes nested package members"); assert.equal((await resolve(glob, "packages/excluded/app")).contract, "JS_STANDALONE", "a definitely excluded package remains independently deployable");
    const mixed = join(root, "mixed"); await mkdir(mixed); await write(mixed, "pnpm-workspace.yaml", "packages:\n  - packages/*\n"); await write(mixed, "pnpm-lock.yaml", "lockfileVersion: '9.0'\n"); await write(mixed, "packages/member/package.json", packageJson("member")); await write(mixed, "apps/js/package.json", packageJson("independent-js")); await write(mixed, "apps/python/requirements.txt", ""); await write(mixed, "unselected/go.mod", "module ignored");
    assert.equal((await resolve(mixed, "apps/js")).contract, "JS_STANDALONE", "an unrelated workspace cannot capture an independent JS service"); assert.equal((await resolve(mixed, "apps/python")).contract, "PYTHON_STANDALONE", "an unrelated JS workspace cannot capture an independent Python service"); assert.equal((await resolve(mixed, "packages/member")).contract, "JS_WORKSPACE_MEMBER");
    const conflict = join(root, "manager-conflict"); await mkdir(conflict); await write(conflict, "package.json", JSON.stringify({ private: true, packageManager: "npm@10.0.0", workspaces: ["apps/*"] })); await write(conflict, "pnpm-lock.yaml", "lockfileVersion: '9.0'\n"); await write(conflict, "apps/app/package.json", packageJson("conflict-app")); await assert.rejects(() => resolve(conflict, "apps/app"), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED", "conflicting package-manager evidence blocks admission");
    const staticWorkspace = join(root, "static-workspace"); await mkdir(staticWorkspace); await write(staticWorkspace, "package.json", JSON.stringify({ private: true, workspaces: ["apps/*"] })); await write(staticWorkspace, "package-lock.json", "{}"); await write(staticWorkspace, "apps/site/package.json", JSON.stringify({ name: "site", scripts: { build: "vite build" }, devDependencies: { vite: "^6.0.0" } }));
    const staticTarget = await resolve(staticWorkspace, "apps/site"); assert.equal(staticTarget.contract, "JS_WORKSPACE_MEMBER"); assert.equal(staticTarget.execution.startCommand, null, "a static workspace app seals only its package-targeted build command");
    const nestedBoundary = join(root, "nested-boundary"); await mkdir(nestedBoundary); await write(nestedBoundary, "package.json", JSON.stringify({ private: true, workspaces: ["packages/*"] })); await write(nestedBoundary, "packages/platform/package.json", JSON.stringify({ private: true, workspaces: ["apps/*"] })); await write(nestedBoundary, "packages/platform/apps/app/package.json", packageJson("nested-boundary-app", { helper: "file:../../../shared" })); await write(nestedBoundary, "packages/shared/package.json", packageJson("shared")); await assert.rejects(() => resolve(nestedBoundary, "packages/platform/apps/app"), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED", "workspace local dependencies must remain inside the canonical nested build root");

    // npm, Yarn, Bun, Nx, Turbo and Lerna are all repository-owned workspace evidence.
    for (const [name, rootManifest, marker] of [
      ["npm", JSON.stringify({ private: true, workspaces: ["apps/*"] }), "package-lock.json"],
      ["yarn", JSON.stringify({ private: true, workspaces: ["apps/*"] }), "yarn.lock"],
      ["bun", JSON.stringify({ private: true, workspaces: ["apps/*"] }), "bun.lockb"],
      ["nx", JSON.stringify({ private: true, workspaces: ["apps/*"] }), "nx.json"],
      ["turbo", JSON.stringify({ private: true, workspaces: ["apps/*"] }), "turbo.json"],
      ["lerna", JSON.stringify({ private: true, workspaces: ["apps/*"] }), "lerna.json"],
    ] as const) {
      const fixture = join(root, name); await mkdir(fixture); await write(fixture, "package.json", rootManifest); await write(fixture, marker, marker === "lerna.json" ? JSON.stringify({ packages: ["apps/*"] }) : "{}"); await write(fixture, "apps/api/package.json", packageJson(`@${name}/api`)); await write(fixture, "apps/shared/package.json", packageJson(`@${name}/shared"`.replace('"', '')));
      const target = await resolve(fixture, "apps/api"); assert.equal(target.strategy, "workspace", `${name} declared workspace membership must retain the root build scope without a sibling dependency`); assert.equal(target.contract, "JS_WORKSPACE_MEMBER"); assert.equal(target.workspaceRoot, "."); assert.equal(target.buildRoot, "."); assert.equal(target.installRoot, "."); assert.equal(target.packageIdentity, `@${name}/api`); assert.equal(target.execution.packageTarget, `@${name}/api`);
    }
    const nested = join(root, "nested"); await mkdir(nested); await write(nested, "package.json", JSON.stringify({ private: true, workspaces: ["packages/*"] })); await write(nested, "packages/platform/package.json", JSON.stringify({ private: true, workspaces: ["apps/*"] })); await write(nested, "packages/platform/apps/web/package.json", packageJson("@nested/web"));
    assert.equal((await resolve(nested, "packages/platform/apps/web")).workspaceRoot, "packages/platform", "nearest nested workspace owns its member");
    const local = join(root, "local-path"); await mkdir(local); await write(local, "service/package.json", packageJson("local-service", { helper: "file:../helper" })); await write(local, "helper/package.json", packageJson("helper")); await assert.rejects(() => resolve(local, "service"), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED");
    const cycle = join(root, "cycle"); await mkdir(cycle); await write(cycle, "package.json", JSON.stringify({ private: true, workspaces: ["packages/*"] })); await write(cycle, "packages/app/package.json", packageJson("app", { library: "workspace:*" })); await write(cycle, "packages/library/package.json", packageJson("library", { app: "workspace:*" })); assert.deepEqual((await resolve(cycle, "packages/app")).dependencyPaths, ["packages/library"], "dependency cycles are bounded and do not create another deployed service");
    const python = join(root, "python"); await mkdir(python); await write(python, "api/pyproject.toml", "[project]\nname = 'api'\n"); const pythonTarget = await resolve(python, "api"); assert.equal(pythonTarget.contract, "PYTHON_STANDALONE"); assert.equal(pythonTarget.strategy, "python_local"); await write(python, "api/requirements.txt", "-e ../shared\n"); await write(python, "shared/pyproject.toml", "[project]\nname = 'shared'\n"); await assert.rejects(() => resolve(python, "api"), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED");
    const pythonCases = join(root, "python-cases"); await mkdir(pythonCases); await write(pythonCases, "empty/requirements.txt", ""); assert.equal((await resolve(pythonCases, "empty")).contract, "PYTHON_STANDALONE", "an empty requirements file is still Python packaging evidence"); await write(pythonCases, "pep/pyproject.toml", "[project]\nname='pep'\ndependencies=['shared @ file://../shared']\n"); await write(pythonCases, "shared/pyproject.toml", "[project]\nname='shared'\n"); await assert.rejects(() => resolve(pythonCases, "pep"), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED", "PEP 508 repository-local file dependencies block Python standalone admission"); await write(pythonCases, "pyproject.toml", "[tool.uv.workspace]\nmembers = ['uv/*']\n"); await write(pythonCases, "uv/app/pyproject.toml", "[project]\nname='uv-app'\n"); await assert.rejects(() => resolve(pythonCases, "uv/app"), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED", "uv workspace members are not Python standalone services");
    for (const tool of ["poetry", "uv", "pdm", "pipenv"]) { const fixture = join(root, tool); await mkdir(fixture); if (tool === "pipenv") await write(fixture, "Pipfile", "[packages]\n"); else await write(fixture, "pyproject.toml", `[tool.${tool}]\n`); assert.equal((await resolve(fixture, ".")).contract, "PYTHON_STANDALONE"); }
    const duplicate = join(root, "duplicate"); await mkdir(duplicate); await write(duplicate, "package.json", JSON.stringify({ private: true, workspaces: ["packages/*"] })); await write(duplicate, "packages/a/package.json", packageJson("same")); await write(duplicate, "packages/b/package.json", packageJson("same")); await assert.rejects(() => resolve(duplicate, "packages/a"), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED");
    const missing = join(root, "missing"); await mkdir(missing); await write(missing, "package.json", JSON.stringify({ private: true, workspaces: ["packages/*"] })); await write(missing, "packages/app/package.json", packageJson("app", { missing: "workspace:*" })); await assert.rejects(() => resolve(missing, "packages/app"), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED");
    const uncertain = join(root, "uncertain"); await mkdir(uncertain); await write(uncertain, "pnpm-workspace.yaml", "packages: [\n"); await write(uncertain, "packages/app/package.json", packageJson("app")); await assert.rejects(() => resolve(uncertain, "packages/app"), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED");
    for (const [name, manifest] of [["go", "go.mod"], ["java", "pom.xml"], ["php", "composer.json"], ["ruby", "Gemfile"]] as const) { const fixture = join(root, name); await mkdir(fixture); await write(fixture, manifest, "fixture"); await assert.rejects(() => resolve(fixture, "."), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED"); }
    const multiServiceSource = new RepositorySourceService(resolver, {} as any) as any;
    await write(pnpm, "unsupported/go.mod", "module unsupported");
    multiServiceSource.checkout = async () => ({ workspacePath: pnpm, sourceSha: sha });
    multiServiceSource.cleanup = async () => undefined;
    await assert.rejects(
      () => multiServiceSource.resolveBuildTargetsAtExactSha({ repositoryUrl: "https://github.com/example/application", branch: "main", sourceSha: sha, services: [{ serviceId, serviceDirectory: "packages/client" }, { serviceId: "22222222-2222-4222-8222-222222222222", serviceDirectory: "unsupported" }] }),
      (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED",
      "one unsupported service blocks a multi-service source admission before a dispatch payload can exist",
    );
    await assert.rejects(() => resolve(pnpm, "packages/client", { buildRoot: "packages/client", selectedPackage: "@fixture/client" }), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_DEPLOYMENT_CONTRACT_UNSUPPORTED");
    await symlink("/tmp", join(root, "escape")); await assert.rejects(() => resolve(root, "escape"), (error: unknown) => error instanceof BuildTargetResolutionError && error.code === "DG_BUILD_TARGET_INVALID");
    console.log("BUILD_TARGET_RESOLUTION=PASS SERVICE_AUTHORITY=USER_SELECTED BUILD_SCOPE_AUTHORITY=EXACT_SHA_CANONICAL");
  } finally { await rm(root, { recursive: true, force: true }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
