import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { managedDatabaseEfsCreationToken, MANAGED_DATABASE_PERSISTENCE_TAG } from "../src/projects/managed-database-identity";

const root = resolve(__dirname, "../..");
const read = (path: string) => readFileSync(resolve(root, path), "utf8");
const workflow = read(".github/workflows/deployguard-reusable.yml");
const deployment = read("backend/src/projects/github-actions-deployment.service.ts");
const generation = read("backend/src/projects/deployment-generation.service.ts");
const migration = read("backend/src/migrations/1760000072000-NoConflictGenerationArchitecture.ts");
const currentState = read("backend/src/projects/current-state/project-current-state.service.ts");
const cleanup = read("backend/src/projects/generation-cleanup-policy.ts");
const capability = read("backend/src/projects/github-actions-aws-capability-contract.ts");
const frontend = read("frontend/src/components/projects/ProjectOverviewLifecycle.jsx");

const projectId = "9ffe6827-f55a-4469-ac80-64530f8cea2e";
assert.ok(managedDatabaseEfsCreationToken(projectId, "dev").length <= 64);
assert.equal(MANAGED_DATABASE_PERSISTENCE_TAG, "project");
assert.match(deployment, /createCandidate/);
assert.match(deployment, /promoteVerified/);
assert.match(deployment, /retiredGenerationCleanup/);
assert.match(generation, /DeploymentGenerationStatus\.CLEANUP_PENDING/);
assert.match(generation, /generation-promote:/);
assert.match(migration, /UQ_project_deployment_generation_live/);
assert.match(migration, /UQ_project_deployment_generation_candidate/);
assert.match(migration, /UQ_project_environment_route_priority/);
assert.match(currentState, /generationState/);
assert.match(frontend, /Immutable generations/);
assert.match(cleanup, /NON_GENERATION_RESOURCE_FIELDS/);
for (const forbidden of ["vpcId", "ecsClusterArn", "albArn", "ecrRepositoryName", "runtimeSecretName", "efsFileSystemId"]) assert.match(cleanup, new RegExp(forbidden));
assert.match(workflow, /Prepare project-scoped persistence/);
assert.match(workflow, /project\/terraform\.tfstate/);
assert.match(workflow, /retiredGenerationCleanup\.generationId/);
assert.match(workflow, /EXPECTED_STATE_KEY="projects\/\$PROJECT_ID\/\$ENVIRONMENT_NAME\/\$RETIRED_GENERATION_ID\/terraform\.tfstate"/);
assert.match(workflow, /cleanup_pending/);
assert.match(workflow, /platformFoundation\.ecsClusterArn/);
assert.match(workflow, /platformFoundation\.listenerArn/);
assert.doesNotMatch(workflow, /resource "aws_ecs_cluster" "app"/);
assert.doesNotMatch(workflow, /resource "aws_lb" "app"/);
assert.match(capability, /CreateRule/);
assert.match(capability, /SetRulePriorities/);
assert.match(capability, /DeployGuardScope/);

console.log("Global platform integration checks passed: isolated generations, shared compute/routing, project persistence, bounded cleanup, current-state projection, and IAM scope.");
