import "reflect-metadata";
import { strict as assert } from "node:assert";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { DeploymentRequirementResolverService } from "../src/projects/deployment-requirement-resolver.service";
import { CanonicalBuildTarget, canonicalBuildTarget } from "../src/projects/build-target";

const resolver = new DeploymentRequirementResolverService(); const sha = "a".repeat(40); const first = "11111111-1111-4111-8111-111111111111"; const second = "22222222-2222-4222-8222-222222222222";
const fixtureDatabaseAuthority = "repository" + ":fixture-only" + "@db";
const target = (serviceId: string, directory = ".") => ({ serviceId, target: canonicalBuildTarget({ resolverVersion: "deployguard.build-target/v2", sourceSha: sha, serviceDirectory: directory, workspaceRoot: ".", buildRoot: directory, installRoot: directory, packageIdentity: "fixture", contract: "JS_STANDALONE", execution: { packageTarget: null, packageManager: "npm", buildCommand: null, startCommand: null }, dependencyPaths: [], strategy: "isolated", status: "resolved", evidence: {}, override: null }) });
const resolve = (root: string, variables: any[] = [], database: any = null, targets = [target(first)]) => resolver.resolve(root, { sourceSha: sha, targets, variables, managedDatabase: database });
void (async () => {
  const root = await mkdtemp(join(tmpdir(), "deployguard-requirements-"));
  try {
    await writeFile(join(root, ".env.example"), "JWT_SECRET=\n# optional\nANALYTICS_KEY=\nPUBLIC_URL=https://example.test\nVITE_API_URL=\n");
    let admission = await resolve(root); assert.equal(admission.status, "INPUT_REQUIRED"); assert.deepEqual(admission.unresolvedRequired, [`${first}:JWT_SECRET`, `${first}:VITE_API_URL`]); assert.ok(admission.requirements.some((item) => item.key === "PORT" && item.owner === "platform" && item.resolvedStatus === "provided")); assert.ok(admission.requirements.some((item) => item.key === "HOST" && item.resolvedStatus === "provided")); assert.ok(admission.requirements.some((item) => item.key === "ANALYTICS_KEY" && item.required === false)); assert.ok(admission.requirements.some((item) => item.key === "PUBLIC_URL" && item.owner === "repository_default"));
    admission = await resolve(root, [{ serviceId: first, key: "JWT_SECRET", isSecret: true, scope: "runtime" }, { serviceId: first, key: "VITE_API_URL", isSecret: false, scope: "build" }]); assert.equal(admission.status, "READY"); const same = await resolve(root, [{ serviceId: first, key: "JWT_SECRET", isSecret: true, scope: "runtime" }, { serviceId: first, key: "VITE_API_URL", isSecret: false, scope: "build" }]); assert.equal(admission.fingerprint, same.fingerprint);
    const configuredVariables = [{ serviceId: first, key: "JWT_SECRET", isSecret: true, scope: "runtime" as const }, { serviceId: first, key: "VITE_API_URL", isSecret: false, scope: "build" as const }];
    for (const engine of ["postgres", "mysql", "mongodb"] as const) { const managed = await resolve(root, configuredVariables, { engine, attachedServiceId: first }); assert.equal(managed.status, "READY"); assert.ok(managed.requirements.some((item) => item.key === "DATABASE_URL" && item.owner === "managed_service" && item.resolvedStatus === "provided")); assert.equal(managed.managedDatabaseUrlSchemes[first], engine === "postgres" ? "postgresql" : engine); }
    await writeFile(join(root, "docker-compose.yml"), `services:\n  api:\n    environment:\n      - DATABASE_URL=postgresql+psycopg://${fixtureDatabaseAuthority}:5432/repository\n`);
    let managedScheme = await resolve(root, configuredVariables, { engine: "postgres", attachedServiceId: first }); assert.equal(managedScheme.status, "READY"); assert.equal(managedScheme.managedDatabaseUrlSchemes[first], "postgresql+psycopg", "fastAPI-101's declared Psycopg v3 SQLAlchemy scheme is preserved without its credentials or host");
    await writeFile(join(root, "docker-compose.yml"), `services:\n  api:\n    environment:\n      DATABASE_URL: postgresql+psycopg2://${fixtureDatabaseAuthority}/repository\n`);
    managedScheme = await resolve(root, configuredVariables, { engine: "postgres", attachedServiceId: first }); assert.equal(managedScheme.managedDatabaseUrlSchemes[first], "postgresql+psycopg2");
    await writeFile(join(root, "docker-compose.yml"), `services:\n  api:\n    environment:\n      DATABASE_URL: postgresql://${fixtureDatabaseAuthority}/repository\n`);
    managedScheme = await resolve(root, configuredVariables, { engine: "postgres", attachedServiceId: first }); assert.equal(managedScheme.managedDatabaseUrlSchemes[first], "postgresql", "generic PostgreSQL remains generic when no driver contract exists");
    await writeFile(join(root, "docker-compose.yml"), `services:\n  api:\n    environment:\n      MYSQL_URL: mysql+pymysql://${fixtureDatabaseAuthority}/repository\n`);
    managedScheme = await resolve(root, configuredVariables, { engine: "mysql", attachedServiceId: first }); assert.equal(managedScheme.managedDatabaseUrlSchemes[first], "mysql+pymysql", "driver-specific MySQL schemes are preserved generically");
    await writeFile(join(root, "docker-compose.yml"), `services:\n  api:\n    environment:\n      DATABASE_URL: mysql+pymysql://${fixtureDatabaseAuthority}/repository\n`);
    managedScheme = await resolve(root, configuredVariables, { engine: "postgres", attachedServiceId: first }); assert.equal(managedScheme.status, "BLOCKED"); assert.match(managedScheme.validationBlockers.join("\n"), /does not match the attached postgres engine/);
    await writeFile(join(root, "docker-compose.yml"), `services:\n  api:\n    environment:\n      - DATABASE_URL=postgresql+psycopg://${fixtureDatabaseAuthority}/repository\n      - POSTGRES_URL=postgresql+psycopg2://${fixtureDatabaseAuthority}/repository\n`);
    managedScheme = await resolve(root, configuredVariables, { engine: "postgres", attachedServiceId: first }); assert.equal(managedScheme.status, "BLOCKED"); assert.match(managedScheme.validationBlockers.join("\n"), /Conflicting managed database consumer URL schemes/);
    await writeFile(join(root, "docker-compose.yml"), `services:\n  api:\n    environment:\n      DATABASE_URL: postgresql+bad+driver://${fixtureDatabaseAuthority}/repository\n`);
    managedScheme = await resolve(root, configuredVariables, { engine: "postgres", attachedServiceId: first }); assert.equal(managedScheme.status, "BLOCKED"); assert.match(managedScheme.validationBlockers.join("\n"), /scheme 'postgresql\+bad\+driver'.*invalid/);
    await writeFile(join(root, "docker-compose.yml"), "");
    const prohibited = await resolve(root, [{ serviceId: first, key: "PORT", isSecret: false, scope: "runtime" }, { serviceId: first, key: "JWT_SECRET", isSecret: true, scope: "runtime" }, { serviceId: first, key: "VITE_API_URL", isSecret: false, scope: "build" }]); assert.equal(prohibited.status, "BLOCKED"); assert.deepEqual(prohibited.prohibitedOverrides, [`${first}:PORT`]);
    await writeFile(join(root, "Dockerfile"), "ARG JWT_SECRET\nENV JWT_SECRET=value\n"); const conflict = await resolve(root, [{ serviceId: first, key: "JWT_SECRET", isSecret: true, scope: "runtime" }, { serviceId: first, key: "VITE_API_URL", isSecret: false, scope: "build" }]); assert.equal(conflict.status, "BLOCKED"); assert.ok(conflict.duplicateConflicts.includes(`${first}:JWT_SECRET`)); await writeFile(join(root, "Dockerfile"), "");
    await mkdir(join(root, "api")); await mkdir(join(root, "web")); await writeFile(join(root, "api", ".env.sample"), "API_TOKEN=\n"); await writeFile(join(root, "web", "deployguard.requirements.json"), JSON.stringify({ requirements: [{ key: "SENDGRID_API_KEY", required: true, secret: true }, { key: "WEB_ONLY", required: false }] })); const multi = await resolve(root, [{ serviceId: first, key: "API_TOKEN", isSecret: true, scope: "runtime" }], null, [target(first, "api"), target(second, "web")]); assert.equal(multi.status, "INPUT_REQUIRED"); assert.deepEqual(multi.unresolvedRequired, [`${second}:SENDGRID_API_KEY`]);
    await writeFile(join(root, "index.js"), "process.env.ARBITRARY_ENV\n"); const arbitrary = await resolve(root, [{ serviceId: first, key: "JWT_SECRET", isSecret: true, scope: "runtime" }, { serviceId: first, key: "VITE_API_URL", isSecret: false, scope: "build" }]); assert.equal(arbitrary.status, "READY", "arbitrary source references are not deterministic blockers"); assert.doesNotMatch(JSON.stringify(arbitrary), /JWT_SECRET[^\"]*secret-value/, "admission evidence contains no plaintext values");
    await writeFile(join(root, ".env.example"), "JWT_SECRET=\nVITE_API_URL=\nNEW_REQUIRED=\n"); const changed = await resolve(root, [{ serviceId: first, key: "JWT_SECRET", isSecret: true, scope: "runtime" }, { serviceId: first, key: "VITE_API_URL", isSecret: false, scope: "build" }]); assert.notEqual(changed.fingerprint, same.fingerprint);
    console.log("DEPLOYMENT_REQUIREMENT_ADMISSION=PASS READY_INPUT_REQUIRED_BLOCKED=1 SECRET_SAFE=1 MANAGED_DATABASE_URL_SCHEME=SEALED");
  } finally { await rm(root, { recursive: true, force: true }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
