import { MigrationInterface, QueryRunner } from "typeorm";

export class CreatePlatformExtensionTables1760000012000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
    const sql = [
      `CREATE TABLE IF NOT EXISTS ai_analysis_sessions (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), user_id integer NOT NULL, project_id uuid NOT NULL, pipeline_run_id uuid NOT NULL, status varchar NOT NULL DEFAULT 'pending', provider varchar, model varchar, provider_mode varchar NOT NULL DEFAULT 'unavailable', initial_context jsonb, last_error varchar, closed_at timestamp, created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS ai_analysis_messages (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), session_id uuid NOT NULL, role varchar NOT NULL, content text NOT NULL, usage_metadata jsonb, created_at timestamp NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS ai_analysis_results (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), session_id uuid NOT NULL, summary text NOT NULL, root_cause text NOT NULL, technical_details text NOT NULL, remediation_steps jsonb NOT NULL, evidence_references jsonb NOT NULL, limitations text NOT NULL, confidence decimal(4,3) NOT NULL DEFAULT 0.5, result_mode varchar NOT NULL DEFAULT 'fallback', revision integer NOT NULL DEFAULT 1, created_at timestamp NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS billing_accounts (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), user_id integer NOT NULL UNIQUE, provider_customer_id varchar UNIQUE, provider varchar NOT NULL DEFAULT 'demo', mode varchar NOT NULL DEFAULT 'demo', payment_brand varchar, payment_last4 varchar, payment_exp_month integer, payment_exp_year integer, created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS billing_subscriptions (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), user_id integer NOT NULL UNIQUE, provider_subscription_id varchar UNIQUE, plan varchar NOT NULL DEFAULT 'free', status varchar NOT NULL DEFAULT 'active', provider varchar NOT NULL DEFAULT 'demo', mode varchar NOT NULL DEFAULT 'demo', billing_period_start timestamp, billing_period_end timestamp, cancel_at_period_end boolean NOT NULL DEFAULT false, cancelled_at timestamp, created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS billing_usage_counters (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), user_id integer NOT NULL, metric varchar NOT NULL, period_start date NOT NULL, period_end date NOT NULL, quantity integer NOT NULL DEFAULT 0, created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now(), UNIQUE(user_id, metric, period_start))`,
      `CREATE TABLE IF NOT EXISTS billing_usage_events (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), user_id integer NOT NULL, metric varchar NOT NULL, idempotency_key varchar NOT NULL UNIQUE, quantity integer NOT NULL DEFAULT 1, period_start date NOT NULL, metadata jsonb, created_at timestamp NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS billing_checkout_sessions (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), user_id integer NOT NULL, provider_session_id varchar NOT NULL UNIQUE, provider varchar NOT NULL, mode varchar NOT NULL, plan varchar NOT NULL, status varchar NOT NULL DEFAULT 'created', expires_at timestamp, created_at timestamp NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS billing_invoices (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), user_id integer NOT NULL, provider_invoice_id varchar NOT NULL UNIQUE, status varchar NOT NULL, amount_due integer NOT NULL DEFAULT 0, currency varchar NOT NULL DEFAULT 'usd', hosted_invoice_url varchar, invoice_pdf_url varchar, issued_at timestamp, created_at timestamp NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS billing_webhook_events (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), provider_event_id varchar NOT NULL UNIQUE, provider varchar NOT NULL, event_type varchar NOT NULL, status varchar NOT NULL DEFAULT 'received', occurred_at timestamp, processed_at timestamp, safe_metadata jsonb, created_at timestamp NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS notification_preferences (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), user_id integer NOT NULL, project_id uuid NOT NULL, critical_enabled boolean NOT NULL DEFAULT true, success_enabled boolean NOT NULL DEFAULT false, stage_updates_enabled boolean NOT NULL DEFAULT false, channel varchar NOT NULL DEFAULT 'email', created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now(), UNIQUE(user_id, project_id))`,
      `CREATE TABLE IF NOT EXISTS notification_subscriptions (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), user_id integer NOT NULL, project_id uuid NOT NULL, destination varchar NOT NULL, protocol varchar NOT NULL DEFAULT 'email', status varchar NOT NULL DEFAULT 'unconfigured', provider_subscription_arn varchar, confirmed_at timestamp, created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now(), UNIQUE(user_id, project_id, destination))`,
      `CREATE TABLE IF NOT EXISTS notification_deliveries (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), user_id integer NOT NULL, project_id uuid, pipeline_run_id uuid, event_type varchar NOT NULL, deduplication_key varchar NOT NULL UNIQUE, status varchar NOT NULL DEFAULT 'pending', provider_message_id varchar, attempts integer NOT NULL DEFAULT 0, last_error varchar, subject varchar NOT NULL, message text NOT NULL, safe_metadata jsonb, sent_at timestamp, created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS infrastructure_destroy_challenges (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), project_id uuid NOT NULL, user_id integer NOT NULL, environment_name varchar NOT NULL, token_hash varchar NOT NULL, confirmation_phrase varchar NOT NULL, expires_at timestamp NOT NULL, used_at timestamp, created_at timestamp NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS infrastructure_destroy_operations (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), project_id uuid NOT NULL, user_id integer NOT NULL, infrastructure_environment_id uuid NOT NULL, environment_name varchar NOT NULL, status varchar NOT NULL DEFAULT 'queued', queue_job_id varchar, state_backup_reference varchar, preserved_resources jsonb, destroyed_resources jsonb, error_message text, started_at timestamp, completed_at timestamp, created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now())`,
      `CREATE TABLE IF NOT EXISTS terraform_export_artifacts (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), project_id uuid NOT NULL, user_id integer NOT NULL, filename varchar NOT NULL, checksum varchar NOT NULL, size_bytes integer NOT NULL, archive bytea NOT NULL, manifest jsonb NOT NULL, expires_at timestamp NOT NULL, created_at timestamp NOT NULL DEFAULT now())`,
    ];
    for (const statement of sql) await queryRunner.query(statement);
    for (const statement of [
      `CREATE INDEX IF NOT EXISTS idx_ai_sessions_project ON ai_analysis_sessions(project_id, updated_at DESC)`, `CREATE INDEX IF NOT EXISTS idx_ai_messages_session ON ai_analysis_messages(session_id, created_at)`, `CREATE INDEX IF NOT EXISTS idx_ai_results_session ON ai_analysis_results(session_id, revision DESC)`, `CREATE INDEX IF NOT EXISTS idx_usage_events_user ON billing_usage_events(user_id, created_at)`, `CREATE INDEX IF NOT EXISTS idx_notification_deliveries_project ON notification_deliveries(project_id, created_at DESC)`, `CREATE INDEX IF NOT EXISTS idx_destroy_operations_project ON infrastructure_destroy_operations(project_id, created_at DESC)`, `CREATE INDEX IF NOT EXISTS idx_export_artifacts_expiry ON terraform_export_artifacts(expires_at)`]) await queryRunner.query(statement);
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    for (const table of ["terraform_export_artifacts", "infrastructure_destroy_operations", "infrastructure_destroy_challenges", "notification_deliveries", "notification_subscriptions", "notification_preferences", "billing_webhook_events", "billing_invoices", "billing_checkout_sessions", "billing_usage_events", "billing_usage_counters", "billing_subscriptions", "billing_accounts", "ai_analysis_results", "ai_analysis_messages", "ai_analysis_sessions"]) await queryRunner.query(`DROP TABLE IF EXISTS ${table}`);
  }
}
