import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * VERSION-14 instant conversion rules:
 * - created_at/updated_at were generated by PostgreSQL defaults in a UTC
 *   database session and therefore contain UTC wall time;
 * - operational/provider columns were written from JavaScript Date values by
 *   the legacy timestamp-without-time-zone driver in America/New_York and
 *   therefore contain local wall time.
 *
 * The explicit split preserves the meaning observed in the supplied database
 * instead of applying one blanket four-hour shift.
 */
export class Version14LifecycleTimestampsAndFingerprints1760000014000 implements MigrationInterface {
  name = "Version14LifecycleTimestampsAndFingerprints1760000014000";

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "project_detection_profiles" ADD COLUMN IF NOT EXISTS "input_fingerprint" varchar`);
    await queryRunner.query(`ALTER TABLE "project_preflight_reports" ADD COLUMN IF NOT EXISTS "input_fingerprint" varchar`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_detection_input_fingerprint" ON "project_detection_profiles" ("project_id", "input_fingerprint")`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_preflight_input_fingerprint" ON "project_preflight_reports" ("project_id", "input_fingerprint")`);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'project_pipeline_runs_status_enum')
           AND NOT EXISTS (
             SELECT 1 FROM pg_enum e
             JOIN pg_type t ON t.oid = e.enumtypid
             WHERE t.typname = 'project_pipeline_runs_status_enum' AND e.enumlabel = 'apply_disabled'
           ) THEN
          ALTER TYPE "project_pipeline_runs_status_enum" ADD VALUE 'apply_disabled';
        END IF;
      END $$
    `);
    await this.convert(queryRunner, "timestamp without time zone", "timestamp with time zone");
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await this.convert(queryRunner, "timestamp with time zone", "timestamp without time zone", true);
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_preflight_input_fingerprint"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_detection_input_fingerprint"`);
    await queryRunner.query(`ALTER TABLE "project_preflight_reports" DROP COLUMN IF EXISTS "input_fingerprint"`);
    await queryRunner.query(`ALTER TABLE "project_detection_profiles" DROP COLUMN IF EXISTS "input_fingerprint"`);
    // PostgreSQL enum values are intentionally not removed in a down migration:
    // rebuilding a live enum would take stronger locks and risk historical rows.
  }

  private async convert(
    queryRunner: QueryRunner,
    fromType: string,
    toType: string,
    reverse = false
  ) {
    const tables = [
      "users", "audit_logs", "projects", "project_environment_variables",
      "project_detection_profiles", "project_preflight_reports", "project_pipeline_runs",
      "project_pipeline_events", "project_security_scans", "project_security_findings",
      "project_cost_estimates", "project_cost_resource_breakdowns", "project_cost_settings",
      "project_infrastructure_environments", "project_infrastructure_events",
      "project_service_discovery_records", "project_deployment_readiness_snapshots",
      "project_terraform_states", "project_terraform_locks", "project_deployment_queue_items",
      "project_state_validation_results", "project_state_recovery_requests",
      "project_persistent_storage", "project_storage_events", "project_backup_records",
      "project_storage_restore_requests", "project_deployments", "project_stable_releases",
      "project_orchestration_events", "project_spot_interruption_events", "project_rollback_records",
      "project_stage_metrics", "project_pipeline_metric_summaries", "project_runtime_metric_snapshots",
      "project_log_stream_sessions", "project_observability_events", "ai_analysis_sessions",
      "ai_analysis_messages", "ai_analysis_results", "notification_preferences",
      "notification_subscriptions", "notification_deliveries", "infrastructure_destroy_challenges",
      "infrastructure_destroy_operations", "terraform_export_artifacts", "billing_accounts",
      "billing_subscriptions", "billing_usage_counters", "billing_usage_events",
      "billing_checkout_sessions", "billing_invoices", "billing_webhook_events"
    ];
    const columns = await queryRunner.query(
      `SELECT table_name, column_name FROM information_schema.columns
       WHERE table_schema = 'public' AND data_type = $1 AND table_name = ANY($2::text[])
       ORDER BY table_name, ordinal_position`,
      [fromType, tables]
    ) as Array<{ table_name: string; column_name: string }>;

    for (const column of columns) {
      const zone = ["created_at", "updated_at"].includes(column.column_name) ? "UTC" : "America/New_York";
      const expression = reverse
        ? `"${column.column_name}" AT TIME ZONE '${zone}'`
        : `"${column.column_name}" AT TIME ZONE '${zone}'`;
      await queryRunner.query(
        `ALTER TABLE "${column.table_name}" ALTER COLUMN "${column.column_name}" TYPE ${toType} USING ${expression}`
      );
    }
  }
}
