output "image" { value = var.image }
output "aws_region" { value = var.region }
output "ecs_cluster_arn" { value = aws_ecs_cluster.application.arn }
output "ecs_cluster_name" { value = aws_ecs_cluster.application.name }
output "ecs_service_arn" { value = aws_ecs_service.application.id }
output "ecs_service_name" { value = aws_ecs_service.application.name }
output "task_definition_arn" { value = aws_ecs_task_definition.application.arn }
output "alb_arn" { value = aws_lb.application.arn }
output "alb_name" { value = aws_lb.application.name }
output "alb_target_group_arn" { value = aws_lb_target_group.application.arn }
output "alb_target_group_name" { value = aws_lb_target_group.application.name }
output "alb_url" { value = "http://${aws_lb.application.dns_name}" }
output "cloudwatch_log_group_name" { value = aws_cloudwatch_log_group.application.name }
output "application_container_name" { value = "application" }
output "database_efs_file_system_id" { value = var.managed_database_enabled ? aws_efs_file_system.database[0].id : null }
output "database_efs_access_point_id" { value = var.managed_database_enabled ? aws_efs_access_point.database[0].id : null }
