import { useEffect, useState } from "react";
import { getManagedDatabaseReconciliation, getProjectDatabaseTier, resetAndDeployFresh, updateProjectDatabaseTier } from "../../api/projectApi.js";

const empty = { provider: "managed", engine: "postgres", externalHost: "", externalPort: "", databaseName: "app", databaseUser: "deployguard", persistenceEnabled: true, backupEnabled: false };
const engineLabel = (engine) => engine === "mysql" ? "MySQL" : engine === "mongodb" ? "MongoDB" : "PostgreSQL";

export default function DatabaseTierSettings({ projectId, canManage, detection }) {
  const [form, setForm] = useState(empty);
  const [database, setDatabase] = useState(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [reconciliation, setReconciliation] = useState(null);
  const [resetPhrase, setResetPhrase] = useState("");
  useEffect(() => { let cancelled = false; Promise.all([getProjectDatabaseTier(projectId), getManagedDatabaseReconciliation(projectId)]).then(([{ database: value }, { databaseReconciliation }]) => { if (!cancelled) { setDatabase(value); setReconciliation(databaseReconciliation); if (value) setForm({ ...empty, ...value, externalPort: value.externalPort || "" }); } }).catch((caught) => { if (!cancelled) setError(caught.message); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [projectId]);
  function change(event) { const { name, type, checked, value } = event.target; setForm((current) => ({ ...current, [name]: type === "checkbox" ? checked : value })); }
  async function save(event) { event.preventDefault(); setBusy(true); setError(""); setMessage(""); try { const payload = { provider: form.provider, engine: form.engine, databaseName: form.databaseName, databaseUser: form.databaseUser, persistenceEnabled: form.persistenceEnabled, backupEnabled: form.backupEnabled }; if (form.provider === "external") Object.assign(payload, { externalHost: form.externalHost, externalPort: form.externalPort ? Number(form.externalPort) : undefined }); const response = await updateProjectDatabaseTier(projectId, payload); setDatabase(response.database); setMessage("Database configuration saved. Regenerate pre-flight before deploying."); } catch (caught) { setError(caught.message); } finally { setBusy(false); } }
  async function resetDatabase() { setBusy(true); setError(""); setMessage(""); try { const response = await resetAndDeployFresh(projectId, resetPhrase); setMessage(response.deployment?.message || "A fresh deployment generation was submitted."); setResetPhrase(""); const [{ database: value }, { databaseReconciliation }] = await Promise.all([getProjectDatabaseTier(projectId), getManagedDatabaseReconciliation(projectId)]); setDatabase(value); setReconciliation(databaseReconciliation); } catch (caught) { setError(caught.message); } finally { setBusy(false); } }
  const required = Boolean(detection?.deploymentContract?.databaseRequired || detection?.database?.required || database?.requiredByDetection);
  const detectedEngine = engineLabel(detection?.deploymentContract?.databaseEngine || database?.engine);
  return <form className="panel-flat settings-simple-form database-tier-settings" onSubmit={save}>
    <div><p className="eyebrow">Database &amp; storage</p><h2>{required ? `Database setup required · ${detectedEngine}` : "Database tier"}</h2><p className="muted">{required ? `Your app uses ${detectedEngine}. DeployGuard can create a persistent database container for this project. ` : ""}Database persistence is separate from application file storage. DeployGuard never treats localhost as a remote database in ECS.</p></div>
    {loading ? <p className="muted">Loading database settings…</p> : null}{error ? <p className="state error" role="alert">{error}</p> : null}{message ? <p className="state success">{message}</p> : null}
    {reconciliation && reconciliation.state !== "HEALTHY" ? <section className={`state ${reconciliation.deploymentDecision?.deploymentAllowed ? "success" : "error"}`} role="status"><strong>{reconciliation.deploymentDecision?.deploymentAllowed ? "Fresh deployment ready" : reconciliation.title}</strong><p>{reconciliation.deploymentDecision?.reason || reconciliation.message}</p>{reconciliation.recoveryAvailable && !reconciliation.deploymentDecision?.deploymentAllowed ? <small>A verified AWS Backup recovery point is available. Use the database recovery workflow before normal deployment.</small> : null}</section> : null}
    <div className="project-trust-grid" aria-label="Database and file persistence summary"><article><span>Persistent database</span><strong>{form.provider === "managed" && form.persistenceEnabled ? "On" : "Off"}</strong></article><article><span>Application file storage</span><strong>{detection?.deploymentContract?.persistentStorageRequired ? "Unsupported · deployment blocked" : "Not required"}</strong></article><article><span>Database network</span><strong>{form.provider === "managed" ? "Private" : "Not configured"}</strong></article></div>
    <div className="form-grid"><label className="field"><span>Database setup</span><select disabled={!canManage || busy} name="provider" onChange={change} value={form.provider}><option value="managed">DeployGuard managed container</option>{!required ? <option value="none">No database</option> : null}</select></label>
      {form.provider !== "none" ? <label className="field"><span>Engine</span><select disabled={!canManage || busy} name="engine" onChange={change} value={form.engine}><option value="postgres">PostgreSQL</option><option value="mysql">MySQL</option><option value="mongodb">MongoDB</option></select></label> : null}
      {form.provider !== "none" ? <><label className="field"><span>Database name</span><input disabled={!canManage || busy} name="databaseName" onChange={change} value={form.databaseName} /></label><label className="field"><span>Database user</span><input disabled={!canManage || busy} name="databaseUser" onChange={change} value={form.databaseUser} /></label></> : null}</div>
    {form.provider === "managed" ? <div className="database-storage-policy"><label><input checked={form.persistenceEnabled} disabled={!canManage || busy} name="persistenceEnabled" onChange={change} type="checkbox" /> Persist database data on project-scoped encrypted EFS</label><small>The database binding and EFS are reused across application generations. Only full project Destroy removes them. Application uploads require external object storage.</small></div> : null}
    {database?.provider === "managed" ? <dl className="developer-detail-grid"><div><dt>Private service</dt><dd>{database.internalHost || "Created during Terraform apply"}</dd></div><div><dt>Credentials</dt><dd>{database.credentialsConfigured ? "Stored in AWS Secrets Manager" : "Generated during Terraform apply"}</dd></div><div><dt>Database EFS</dt><dd>{reconciliation?.evidence?.currentFileSystem?.available ? "Verified in AWS" : database.efsConfigured ? "Recorded, verification required" : "Pending"}</dd></div><div><dt>Backup requested</dt><dd>{reconciliation?.backup?.requested ? "Yes" : "No"}</dd></div><div><dt>Backup infrastructure</dt><dd>{reconciliation?.backup?.infrastructureActive ? "Active" : "Not verified"}</dd></div><div><dt>Recoverable backup</dt><dd>{reconciliation?.backup?.recoverableRecoveryPointArn ? "Available" : "None verified"}</dd></div></dl> : null}
    {canManage && reconciliation?.resetAllowed && !reconciliation?.deploymentDecision?.deploymentAllowed ? <section className="state warning"><strong>Reset &amp; Deploy Fresh</strong><p>This explicitly retires the proven-unusable database identity, preserves deployment history, and starts a new empty deployment generation. It is not a normal retry.</p><label className="field"><span>Type RESET AND DEPLOY FRESH</span><input disabled={busy} onChange={(event) => setResetPhrase(event.target.value)} value={resetPhrase} /></label><button className="danger-button" disabled={busy || resetPhrase !== "RESET AND DEPLOY FRESH"} onClick={resetDatabase} type="button">Reset &amp; Deploy Fresh</button></section> : null}
    {canManage ? <button className="button" disabled={busy || loading} type="submit">{busy ? "Saving…" : "Save database configuration"}</button> : null}
  </form>;
}
