import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { cancelDestroy, createCloudCleanupChallenge, createDestroyChallenge, downloadProjectCleanupReport, getDestroyReview, getDestroyStatus, getProjectResources, refreshProjectResources, requestCloudCleanup, requestDestroy, retryDestroy, updateProjectResourceTtl } from "../../api/platformApi.js";
import { markCloudResourcesManualReview } from "../../api/adminApi.js";

const activeStatuses = new Set(["queued", "running"]);
const tabs = ["all", "safe_cleanup", "terraform_destroy", "manual_review", "protected", "deleted", "errors"];
const statusLabels = { queued: "Destroy queued", running: "Destroy running", completed: "Destroy completed", failed: "Destroy failed", cancelled: "Destroy cancelled" };

export default function DestroyInfrastructurePanel({ projectId, canManage, isAdmin = false, hasInfrastructure = false, currentState = null }) {
  const [review, setReview] = useState(null);
  const [challenge, setChallenge] = useState(null);
  const [operation, setOperation] = useState(null);
  const [phrase, setPhrase] = useState("");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState("");
  const [inventory, setInventory] = useState(null);
  const [cleanupChallenge, setCleanupChallenge] = useState(null);
  const [cleanupPhrase, setCleanupPhrase] = useState("");
  const [selectedResources, setSelectedResources] = useState([]);
  const [tab, setTab] = useState("all");
  const [ttlHours, setTtlHours] = useState("4");
  const [customTtl, setCustomTtl] = useState("");
  const [ttlEnvironmentType, setTtlEnvironmentType] = useState("testing");
  const [ttlConfirmation, setTtlConfirmation] = useState("");
  const isActive = activeStatuses.has(operation?.status);
  const eventsUrl = review?.environment?.pipelineRunId ? `/projects/${projectId}/logs?run=${encodeURIComponent(review.environment.pipelineRunId)}` : `/projects/${projectId}/logs`;

  useEffect(() => {
    if (!canManage) return undefined;
    let cancelled = false;
    getProjectResources(projectId).then((value) => { if (!cancelled) { setInventory(value); setTtlEnvironmentType(value.ttl?.environmentType === "preview" ? "preview" : "testing"); } }).catch((caught) => { if (!cancelled) setError(caught.message); });
    if (hasInfrastructure) Promise.all([getDestroyReview(projectId), getDestroyStatus(projectId)]).then(([nextReview, latest]) => { if (!cancelled) { setReview(nextReview); setOperation(latest); } }).catch((caught) => { if (!cancelled) setError(caught.message); });
    return () => { cancelled = true; };
  }, [projectId, canManage, hasInfrastructure]);

  useEffect(() => {
    if (!isActive || !operation?.id) return undefined;
    const timer = window.setInterval(async () => { try { const next = await getDestroyStatus(projectId, operation.id); setOperation(next); if (!activeStatuses.has(next?.status)) await loadRegistry(); } catch (caught) { setError(caught.message); } }, 3000);
    return () => window.clearInterval(timer);
  }, [projectId, operation?.id, isActive]);

  async function loadRegistry() { const next = await getProjectResources(projectId); setInventory(next); setSelectedResources((current) => current.filter((id) => next.resources?.some((resource) => resource.id === id && resource.safeToCleanup))); return next; }
  async function refreshInventory() { setBusy("scan"); setError(""); setNotice(""); try { const next = await refreshProjectResources(projectId); setInventory(next); setSelectedResources(next.resources?.filter((resource) => resource.safeToCleanup && !resource.protected).map((resource) => resource.id) || []); setNotice(next.scan?.errors?.length ? "Inventory completed with errors. Unverified resources remain protected." : "AWS inventory refreshed."); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function exportReport() { setBusy("export"); setError(""); try { await downloadProjectCleanupReport(projectId); setNotice("Sanitized project resource report exported."); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function beginDestroy() { setBusy("challenge"); setError(""); try { setChallenge(await createDestroyChallenge(projectId, review.environment.name)); setPhrase(""); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function executeDestroy() { if (phrase !== "DESTROY") return; setBusy("destroy"); setError(""); try { const next = await requestDestroy(projectId, { challengeId: challenge.challengeId, challengeToken: challenge.challengeToken, confirmationPhrase: phrase, environmentName: review.environment.name, deletePersistentDatabaseData: true, databaseDataConfirmation: "DELETE PERSISTENT DATABASE DATA" }); setOperation(next); setChallenge(null); setPhrase(""); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function cancel() { setBusy("cancel"); setError(""); try { setOperation(await cancelDestroy(projectId, operation.id)); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function retry() { setBusy("retry"); setError(""); try { setChallenge(await retryDestroy(projectId, operation.id)); setPhrase(""); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function beginCleanup(selectAll = false) { if (selectAll) setSelectedResources(resources.filter((resource) => resource.safeToCleanup && !resource.protected).map((resource) => resource.id)); setBusy("cleanup-challenge"); setError(""); try { setCleanupChallenge(await createCloudCleanupChallenge(projectId, review?.environment?.name || "dev")); setCleanupPhrase(""); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function executeCleanup() { if (cleanupPhrase !== "DELETE CLOUD RESOURCES") return; setBusy("cleanup"); setError(""); try { const safeIds = resources.filter((resource) => selectedResources.includes(resource.id) && resource.safeToCleanup && !resource.protected).map((resource) => resource.resourceKey || resource.id); const next = await requestCloudCleanup(projectId, { challengeId: cleanupChallenge.challengeId, challengeToken: cleanupChallenge.challengeToken, confirmationPhrase: cleanupPhrase, environmentName: review?.environment?.name || "dev", selectedResourceIds: safeIds }); setOperation(next); setCleanupChallenge(null); setCleanupPhrase(""); await loadRegistry(); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function markManualReview() { if (!selectedResources.length) return; setBusy("manual"); setError(""); try { await markCloudResourcesManualReview(selectedResources); setNotice("Selected resources marked for manual review."); setSelectedResources([]); await loadRegistry(); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function scheduleTtl() { setBusy("ttl"); setError(""); try { const timing = ttlHours === "custom" ? { ttlExpiresAt: new Date(customTtl).toISOString() } : { ttlHours: Number(ttlHours) }; const ttl = await updateProjectResourceTtl(projectId, { environmentType: ttlEnvironmentType, autoDestroyEnabled: true, confirmationPhrase: ttlConfirmation, ...timing }); setInventory((current) => ({ ...current, ttl })); setTtlConfirmation(""); setNotice(`Auto-destroy scheduled at ${new Date(ttl.ttlExpiresAt).toLocaleString()}.`); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function disableTtl() { setBusy("ttl"); setError(""); try { const ttl = await updateProjectResourceTtl(projectId, { environmentType: inventory?.ttl?.environmentType || "testing", autoDestroyEnabled: false }); setInventory((current) => ({ ...current, ttl })); setNotice("Automatic destroy disabled."); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  function toggleResource(id) { setSelectedResources((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); }

  const resources = inventory?.resources || [];
  const visible = useMemo(() => tab === "all" ? resources : tab === "errors" ? [] : tab === "deleted" ? resources.filter((resource) => resource.deleteStatus === "deleted") : resources.filter((resource) => resource.cleanupEligibility === tab && resource.deleteStatus !== "deleted"), [resources, tab]);
  const categoryGroups = useMemo(() => [
    ["Compute", ["ecs_cluster", "ecs_service", "ecs_task", "ecs_task_definition"]],
    ["Networking", ["vpc", "subnet", "route_table", "internet_gateway", "nat_gateway", "elastic_ip", "security_group", "network_interface", "load_balancer", "target_group", "listener", "cloud_map_namespace", "cloud_map_service"]],
    ["Images", ["ecr_repository", "ecr_image", "ecr_lifecycle_policy"]], ["Secrets", ["secret"]],
    ["Logs", ["log_group", "log_stream"]], ["Storage", ["efs", "efs_access_point", "efs_mount_target", "kms_key", "backup_vault", "backup_plan"]],
    ["State", ["terraform_state", "terraform_state_backup", "terraform_lockfile", "state_bucket"]], ["IAM", ["iam_role", "iam_policy"]],
  ].map(([label, types]) => ({ label, count: resources.filter((resource) => types.includes(resource.category) && resource.deleteStatus !== "deleted").length })), [resources]);
  const selectedSafe = resources.filter((resource) => selectedResources.includes(resource.id) && resource.safeToCleanup && !resource.protected);
  const grouped = inventory?.groups || { terraformStack: { count: 0 }, directCleanup: { ecrRepositories: [], logs: [], secrets: [], oldTaskDefinitions: [] }, protected: [], manualReview: [] };
  const operationIsHistorical = operation?.status === "completed" && ["provisioned", "provisioning"].includes(currentState?.infrastructureStatus);
  const operationLabel = operationIsHistorical ? "Previous cleanup operation completed" : operation ? statusLabels[operation.status] || operation.status : "Not requested";
  if (!canManage) return null;

  return <section className="project-resource-cleanup">
    {currentState ? <div className="cleanup-authoritative-strip"><Status label="Infrastructure" value={currentState.infrastructureStatus} /><Status label="Resources" value={currentState.resourceStatus} /><Status label="Cleanup" value={currentState.cleanupStatus} /><Status label="Cloud verification" value={currentState.cloudVerificationStatus} /></div> : null}
    <div className="resource-cleanup-heading"><div><p className="eyebrow">Infrastructure lifecycle</p><h2>Resource Cleanup</h2><p>Inspect every cloud resource attributed to this project, then destroy only through verified project scope.</p></div><div className="quick-actions"><button className="subtle-button" disabled={Boolean(busy)} onClick={exportReport} type="button">Export report</button>{isAdmin ? <button className="secondary-button" disabled={Boolean(busy)} onClick={refreshInventory} type="button">{busy === "scan" ? "Scanning AWS…" : "Refresh inventory"}</button> : null}</div></div>
    <div className="resource-cleanup-status-grid"><Status label="Current project stack" value={currentState?.infrastructureStatus === "provisioned" ? "Present" : hasInfrastructure ? review?.environment?.status || "Recorded" : "Not created"} /><Status label="Cleanup history" value={operationLabel} /><Status label="Current cleanup recommendation" value={currentState?.deploymentReconciliation?.projectCleanupRecommended ? "Review verified residue" : "None"} /><Status label="Last scan" value={inventory?.scan?.completedAt ? new Date(inventory.scan.completedAt).toLocaleString() : "Not scanned"} /></div>
    <div className="cleanup-primary-cards"><article><span>Terraform-managed stack</span><strong>{grouped.terraformStack.count} resources</strong><p>Network, ECS, ALB, Cloud Map, EventBridge, EFS and IAM are removed together through this project's Terraform state.</p><button className="danger-button" disabled={Boolean(busy) || isActive || !review?.canRequest} onClick={beginDestroy} type="button">Destroy entire project infrastructure</button></article><article><span>Verified residue</span><strong>{currentState?.deploymentReconciliation?.verifiedResidue?.length || 0} resources</strong><p>Direct leftover cleanup is available only after an intentional Terraform destroy and verified inventory.</p><button className="secondary-button" disabled={!isAdmin || Boolean(busy) || operation?.status !== "completed" || !inventory?.summary?.safeCleanup || !inventory?.summary?.verified} onClick={() => beginCleanup(true)} type="button">Clean verified residue</button></article><article className="protected"><span>Protected resources</span><strong>{grouped.protected.length}</strong><p>State bucket, state objects/backups, shared infrastructure and active locks are view-only.</p></article><article><span>Unknown / manual review</span><strong>{grouped.manualReview.length}</strong><p>Unknown ownership is never deleted automatically.</p></article></div>
    {inventory?.ttl ? <div className="ttl-control"><div><span>Testing / preview TTL</span><strong>{inventory.ttl.autoDestroyEnabled ? `Auto-destroy scheduled at ${new Date(inventory.ttl.ttlExpiresAt).toLocaleString()}` : "Automatic destroy is off"}</strong><small>TTL cleanup never targets production. Type SCHEDULE AUTO DESTROY to confirm.</small></div><select aria-label="Environment type" onChange={(event) => setTtlEnvironmentType(event.target.value)} value={ttlEnvironmentType}><option value="testing">Testing</option><option value="preview">Preview</option></select><select aria-label="TTL duration" onChange={(event) => setTtlHours(event.target.value)} value={ttlHours}><option value="1">1 hour</option><option value="4">4 hours</option><option value="12">12 hours</option><option value="24">24 hours</option><option value="custom">Custom</option></select>{ttlHours === "custom" ? <input aria-label="Custom TTL expiry" min={new Date().toISOString().slice(0, 16)} onChange={(event) => setCustomTtl(event.target.value)} type="datetime-local" value={customTtl} /> : null}<input aria-label="TTL confirmation" onChange={(event) => setTtlConfirmation(event.target.value)} placeholder="SCHEDULE AUTO DESTROY" value={ttlConfirmation} /><button className="secondary-button" disabled={Boolean(busy) || ttlConfirmation !== "SCHEDULE AUTO DESTROY" || (ttlHours === "custom" && !customTtl)} onClick={scheduleTtl} type="button">{inventory.ttl.autoDestroyEnabled ? "Extend TTL" : "Enable TTL"}</button>{inventory.ttl.autoDestroyEnabled ? <button className="subtle-button" disabled={Boolean(busy)} onClick={disableTtl} type="button">Disable</button> : null}</div> : null}
    <details className="resource-breakdown"><summary>View resource category breakdown</summary><div className="resource-category-grid" aria-label="Project resource categories">{categoryGroups.map((group) => <article key={group.label}><span>{group.label}</span><strong>{group.count}</strong></article>)}</div></details>
    {review?.backend ? <div className="destroy-scope"><span>Project state scope</span><code>{review.backend.stateKey}</code><small>{review.backend.bucket} · {review.backend.region} · the bucket itself is never destroyed</small></div> : null}
    {inventory?.scan?.errors?.length ? <div className="state warning"><strong>Inventory incomplete</strong><ul>{inventory.scan.errors.map((item) => <li key={item}>{item}</li>)}</ul></div> : null}
    {error ? <p className="state error" role="alert">{error}</p> : null}{notice ? <p className="state success">{notice}</p> : null}

    <details className="raw-resource-details"><summary>View individual resource inventory</summary><div className="cleanup-tabs" role="tablist">{tabs.map((value) => <button aria-selected={tab === value} className={tab === value ? "active" : ""} key={value} onClick={() => setTab(value)} role="tab" type="button">{human(value)}</button>)}</div>
    {tab === "errors" ? inventory?.scan?.errors?.length ? <ul className="inventory-error-list">{inventory.scan.errors.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="resource-empty-copy">No inventory errors were recorded by the latest scan.</p> : visible.length ? <div className="cloud-inventory-table project-resource-table"><table><thead><tr><th>Select</th><th>Resource</th><th>Type / service</th><th>Region</th><th>Ownership</th><th>Cleanup path</th><th>Cost risk</th><th>Last seen</th></tr></thead><tbody>{visible.map((resource) => <tr className={resource.costRisk === "high" ? "high-cost-row" : ""} key={resource.id}><td><input aria-label={`Select ${resource.name}`} checked={selectedResources.includes(resource.id)} disabled={!isAdmin || resource.protected || resource.deleteStatus === "deleted"} onChange={() => toggleResource(resource.id)} type="checkbox" /></td><td><strong>{resource.name}</strong><small>{resource.reason}</small></td><td>{human(resource.category)}<small>{resource.awsService}</small></td><td>{resource.region}</td><td>{human(resource.ownershipCategory || resource.ownership)}</td><td><span className={`cleanup-status ${resource.protected ? "protected" : resource.deleteStatus}`}>{human(resource.cleanupEligibility)}</span></td><td><span className={`cost-risk ${resource.costRisk}`}>{resource.costRisk}</span></td><td>{resource.lastSeenAt ? new Date(resource.lastSeenAt).toLocaleString() : "—"}</td></tr>)}</tbody></table></div> : <p className="resource-empty-copy">{inventory?.scan ? `No ${human(tab)} resources were found. ${inventory.summary?.safeCleanup || 0} safe, ${inventory.summary?.manualReview || 0} manual-review, and ${inventory.summary?.protected || 0} protected resources exist across other views.` : "No completed AWS inventory scan exists yet. An administrator can refresh inventory to establish current cloud state."}</p>}</details>

    <div className="resource-cleanup-actions"><div><strong>{operationIsHistorical ? "Previous cleanup operation" : "Current cleanup operation"}</strong><p>Every destructive action requires recent authentication, an exact confirmation, and project-state scoping.</p></div>{operation ? <div className={`destroy-operation ${operation.status}`}><strong>{operationLabel}</strong>{operation.errorMessage ? <p>{operation.errorMessage}</p> : null}<div className="quick-actions"><Link className="subtle-button" to={eventsUrl}>View events</Link>{operation.status === "queued" ? <button className="subtle-button" disabled={Boolean(busy)} onClick={cancel} type="button">Cancel queued destroy</button> : null}{operation.status === "failed" ? <button className="secondary-button" disabled={Boolean(busy) || !review?.canRequest} onClick={retry} type="button">Retry destroy</button> : null}</div></div> : <span className="muted">No cleanup operation yet.</span>}</div>
    {isAdmin ? <div className="resource-cleanup-actions admin-leftovers"><div><strong>Admin leftover cleanup</strong><p>Available only after Terraform destroy completes and a verified scan identifies explicitly supported residue.</p></div><div className="quick-actions"><button className="subtle-button" disabled={Boolean(busy) || !selectedResources.length} onClick={markManualReview} type="button">Mark manual review</button><button className="danger-text-button" disabled={Boolean(busy) || operation?.status !== "completed" || !selectedSafe.length || !inventory?.summary?.verified} onClick={beginCleanup} type="button">Clean selected safe leftovers</button></div></div> : null}

    {challenge ? <Confirm title="Destroy project resources?" phrase="DESTROY" value={phrase} setValue={setPhrase} busy={busy === "destroy"} onCancel={() => setChallenge(null)} onConfirm={executeDestroy}><p>Destroy permanently removes every resource and persistence object owned by the active generation, including managed database EFS data, secrets, images, task definitions, and Terraform state versions.</p></Confirm> : null}
    {cleanupChallenge ? <Confirm title="Clean selected cloud leftovers?" phrase="DELETE CLOUD RESOURCES" value={cleanupPhrase} setValue={setCleanupPhrase} busy={busy === "cleanup"} onCancel={() => setCleanupChallenge(null)} onConfirm={executeCleanup}><p>Only selected resources with exact ownership proof and a supported cleanup operation will be targeted.</p></Confirm> : null}
  </section>;
}

function Status({ label, value }) { return <article><span>{label}</span><strong>{human(value)}</strong></article>; }
function Confirm({ title, phrase, value, setValue, busy, additionalDisabled = false, onCancel, onConfirm, children }) { return <div className="destroy-modal-backdrop"><section aria-modal="true" className="destroy-modal" role="dialog"><p className="eyebrow">Permanent action</p><h2>{title}</h2>{children}<label className="field"><span>Type <strong>{phrase}</strong> to confirm</span><input autoComplete="off" autoFocus onChange={(event) => setValue(event.target.value)} value={value} /></label><div className="destroy-modal-actions"><button className="subtle-button" disabled={busy} onClick={onCancel} type="button">Cancel</button><button className="danger-button" disabled={busy || additionalDisabled || value !== phrase} onClick={onConfirm} type="button">{busy ? "Working…" : "Confirm"}</button></div></section></div>; }
function human(value) { return String(value || "—").replaceAll("_", " "); }
