import { createHash } from "node:crypto";
import { existsSync, statSync } from "node:fs";
import { resolve } from "node:path";

export type WorkflowLifecycleAction = "deploy" | "destroy" | "rollback" | "promote" | "compensate";
export type WorkflowAwsCapabilityScope = { accountId: string; region: string; projectId: string; environmentName: string; generationId: string; terraformStateBucket: string; vpcId: string; managedDatabaseEnabled: boolean };
export type WorkflowAwsCapability = { id: string; area: "sts" | "ecr" | "ecs" | "ec2" | "elbv2" | "logs" | "iam" | "secrets" | "efs" | "s3"; actions: readonly string[]; paths: readonly WorkflowLifecycleAction[]; actionsByPath?: Partial<Record<WorkflowLifecycleAction, readonly string[]>>; resources: (scope: WorkflowAwsCapabilityScope) => string[]; policyResources?: (scope: WorkflowAwsCapabilityScope) => string[]; simulationResources?: (scope: WorkflowAwsCapabilityScope, action: string) => string[]; simulationContext?: (scope: WorkflowAwsCapabilityScope) => Record<string, string[]>; condition?: (scope: WorkflowAwsCapabilityScope) => Record<string, Record<string, string | string[]>>; policyCondition?: (scope: WorkflowAwsCapabilityScope) => Record<string, Record<string, string | string[]>>; when?: (scope: WorkflowAwsCapabilityScope) => boolean };
const TERRAFORM = ["deploy", "destroy", "rollback"] as const;
const all = () => ["*"];
const arn = (s: WorkflowAwsCapabilityScope, service: string, suffix: string) => `arn:aws:${service}:${s.region}:${s.accountId}:${suffix}`;
const role = (s: WorkflowAwsCapabilityScope) => `dg-${s.projectId.replace(/-/g, "").slice(0, 12).toLowerCase()}`;

/** Exact capability contract for infrastructure/railpack-runtime. */
export const WORKFLOW_AWS_CAPABILITY_CONTRACT_VERSION = "deployguard.railpack-runtime-aws/v3";
export const WORKFLOW_AWS_CAPABILITIES: readonly WorkflowAwsCapability[] = [
  { id: "read-discovery", area: "sts", paths: TERRAFORM, actions: ["sts:GetCallerIdentity", "ecr:GetAuthorizationToken", "ecr:DescribeRepositories", "ecr:DescribeImages", "ecs:DescribeClusters", "ecs:DescribeServices", "ecs:DescribeTaskDefinition", "ec2:DescribeSecurityGroups", "ec2:DescribeSubnets", "ec2:DescribeVpcs", "elasticloadbalancing:DescribeLoadBalancers", "elasticloadbalancing:DescribeTargetGroups", "elasticloadbalancing:DescribeListeners", "elasticloadbalancing:DescribeTargetHealth", "logs:DescribeLogGroups", "iam:GetRole", "iam:GetRolePolicy", "iam:ListAttachedRolePolicies", "s3:GetBucketVersioning"], resources: all },
  { id: "terraform-state", area: "s3", paths: TERRAFORM, actions: ["s3:ListBucket", "s3:GetObject", "s3:PutObject", "s3:DeleteObject"], resources: s => [`arn:aws:s3:::${s.terraformStateBucket}`, `arn:aws:s3:::${s.terraformStateBucket}/projects/${s.projectId}/*`], policyResources: s => [`arn:aws:s3:::${s.terraformStateBucket}`, `arn:aws:s3:::${s.terraformStateBucket}/projects/*`] },
  { id: "ecr-image", area: "ecr", paths: ["deploy", "rollback"], actions: ["ecr:CreateRepository", "ecr:BatchCheckLayerAvailability", "ecr:CompleteLayerUpload", "ecr:InitiateLayerUpload", "ecr:PutImage", "ecr:UploadLayerPart", "ecr:BatchGetImage", "ecr:GetDownloadUrlForLayer"], resources: s => [arn(s, "ecr", `repository/deployguard-${s.projectId.toLowerCase()}`)], policyResources: s => [arn(s, "ecr", "repository/deployguard-*")] },
  { id: "logs", area: "logs", paths: TERRAFORM, actions: ["logs:CreateLogGroup", "logs:PutRetentionPolicy", "logs:TagResource", "logs:DeleteLogGroup"], resources: s => [arn(s, "logs", `log-group:/deployguard/${s.projectId}:*`)], policyResources: s => [arn(s, "logs", "log-group:/deployguard/*")] },
  { id: "ecs-runtime", area: "ecs", paths: TERRAFORM, actions: ["ecs:CreateCluster", "ecs:DeleteCluster", "ecs:RegisterTaskDefinition", "ecs:DeregisterTaskDefinition", "ecs:DeleteTaskDefinitions", "ecs:CreateService", "ecs:UpdateService", "ecs:DeleteService", "ecs:DescribeClusters", "ecs:DescribeServices", "ecs:DescribeTaskDefinition", "ecs:TagResource", "ecs:UntagResource"], resources: all },
  { id: "network", area: "ec2", paths: TERRAFORM, actions: ["ec2:CreateSecurityGroup", "ec2:DeleteSecurityGroup", "ec2:AuthorizeSecurityGroupIngress", "ec2:AuthorizeSecurityGroupEgress", "ec2:RevokeSecurityGroupIngress", "ec2:RevokeSecurityGroupEgress", "ec2:CreateTags", "ec2:DeleteTags"], resources: all },
  { id: "load-balancer", area: "elbv2", paths: TERRAFORM, actions: ["elasticloadbalancing:CreateLoadBalancer", "elasticloadbalancing:DeleteLoadBalancer", "elasticloadbalancing:CreateTargetGroup", "elasticloadbalancing:DeleteTargetGroup", "elasticloadbalancing:CreateListener", "elasticloadbalancing:DeleteListener", "elasticloadbalancing:ModifyListener", "elasticloadbalancing:RegisterTargets", "elasticloadbalancing:DeregisterTargets", "elasticloadbalancing:AddTags", "elasticloadbalancing:RemoveTags"], resources: all },
  { id: "execution-role", area: "iam", paths: TERRAFORM, actions: ["iam:CreateRole", "iam:DeleteRole", "iam:AttachRolePolicy", "iam:DetachRolePolicy", "iam:PutRolePolicy", "iam:DeleteRolePolicy", "iam:PassRole", "iam:TagRole", "iam:UntagRole"], resources: s => [`arn:aws:iam::${s.accountId}:role/${role(s)}-*`, "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"], policyResources: s => [`arn:aws:iam::${s.accountId}:role/dg-*`, "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"] },
  { id: "database-secrets", area: "secrets", paths: TERRAFORM, when: s => s.managedDatabaseEnabled, actions: ["secretsmanager:CreateSecret", "secretsmanager:PutSecretValue", "secretsmanager:GetSecretValue", "secretsmanager:DeleteSecret", "secretsmanager:TagResource", "secretsmanager:UntagResource"], resources: s => [arn(s, "secretsmanager", `secret:deployguard/${s.projectId}/*`)], policyResources: s => [arn(s, "secretsmanager", "secret:deployguard/*")] },
  { id: "database-efs", area: "efs", paths: TERRAFORM, when: s => s.managedDatabaseEnabled, actions: ["elasticfilesystem:CreateFileSystem", "elasticfilesystem:DeleteFileSystem", "elasticfilesystem:CreateAccessPoint", "elasticfilesystem:DeleteAccessPoint", "elasticfilesystem:CreateMountTarget", "elasticfilesystem:DeleteMountTarget", "elasticfilesystem:TagResource", "elasticfilesystem:UntagResource"], resources: all },
];
export function capabilitiesFor(action: WorkflowLifecycleAction, scope?: WorkflowAwsCapabilityScope) { return WORKFLOW_AWS_CAPABILITIES.filter(c => c.paths.includes(action) && (!c.when || !scope || c.when(scope))).map(c => c.actionsByPath?.[action] ? { ...c, actions: c.actionsByPath[action]! } : c); }
export function workflowCapabilityPolicy(scope: WorkflowAwsCapabilityScope, onlyActions?: ReadonlySet<string>) { return { Version: "2012-10-17", Statement: WORKFLOW_AWS_CAPABILITIES.filter(c => !c.when || c.when(scope)).flatMap((c, index) => { const Action = c.actions.filter(action => !onlyActions || onlyActions.has(action)); return Action.length ? [{ Sid: `DeployGuard${index + 1}${c.id.replace(/[^A-Za-z0-9]/g, "")}`, Effect: "Allow", Action, Resource: (c.policyResources || c.resources)(scope) }] : []; }) }; }
export function workflowCapabilityFingerprint() { const scope: WorkflowAwsCapabilityScope = { accountId: "000000000000", region: "us-east-1", projectId: "00000000-0000-4000-8000-000000000000", environmentName: "dev", generationId: "11111111-1111-4111-8111-111111111111", terraformStateBucket: "deployguard-contract-state", vpcId: "vpc-00000000000000000", managedDatabaseEnabled: true }; return createHash("sha256").update(`${WORKFLOW_AWS_CAPABILITY_CONTRACT_VERSION}:${JSON.stringify(workflowCapabilityPolicy(scope))}`).digest("hex"); }
const loadedAt = Date.now();
export function workflowCapabilityRuntimeStatus() { const changedFiles = [...new Set([__filename, resolve(process.cwd(), "src/projects/github-actions-aws-capability-contract.ts"), resolve(process.cwd(), "backend/src/projects/github-actions-aws-capability-contract.ts")])].filter(file => existsSync(file) && statSync(file).mtimeMs > loadedAt + 1_000); return { version: WORKFLOW_AWS_CAPABILITY_CONTRACT_VERSION, fingerprint: workflowCapabilityFingerprint(), stale: changedFiles.length > 0, changedFiles }; }
