export type DevOpsTemplateDefinition = {
  templateKey: string;
  ecosystem: string;
  framework: string;
  frameworkVariant: string;
  displayName: string;
  description: string;
  baseImage: string;
  runtimeImage: string;
  usesMultiStageBuild: boolean;
  securityLevel: string;
  defaultPort: number;
  requiredFiles: string[];
  requiredCommands: string[];
  outputMode: string;
  supportedPackageManagers: string[];
  dockerfileTemplatePath: string | null;
  notes: string[];
  warnings: string[];
};

export const DEVOPS_TEMPLATES: DevOpsTemplateDefinition[] = [
  {
    templateKey: "vite-static",
    ecosystem: "node",
    framework: "vite-react",
    frameworkVariant: "vite-static",
    displayName: "Vite Static Docker Template",
    description: "Multi-stage Dockerfile that builds and serves a Vite application.",
    baseImage: "node:22-alpine3.21",
    runtimeImage: "nginxinc/nginx-unprivileged:1.27-alpine",
    usesMultiStageBuild: true,
    securityLevel: "high",
    defaultPort: 8080,
    requiredFiles: ["package.json"],
    requiredCommands: ["install", "build", "start"],
    outputMode: "static",
    supportedPackageManagers: ["npm", "yarn", "pnpm"],
    dockerfileTemplatePath: "templates/docker/node/vite-static.Dockerfile.tpl",
    notes: ["Builds static assets and serves them from an unprivileged nginx runtime."],
    warnings: [],
  },
  {
    templateKey: "nextjs-ssr",
    ecosystem: "node",
    framework: "nextjs",
    frameworkVariant: "nextjs-ssr",
    displayName: "Next.js SSR Docker Template",
    description: "Multi-stage Dockerfile for server-rendered Next.js apps.",
    baseImage: "node:22-alpine3.21",
    runtimeImage: "node:22-alpine3.21",
    usesMultiStageBuild: true,
    securityLevel: "high",
    defaultPort: 3000,
    requiredFiles: ["package.json"],
    requiredCommands: ["install", "build", "start"],
    outputMode: "server",
    supportedPackageManagers: ["npm", "yarn", "pnpm"],
    dockerfileTemplatePath: "templates/docker/node/nextjs-ssr.Dockerfile.tpl",
    notes: ["Runs as a non-root user."],
    warnings: [],
  },
  {
    templateKey: "nextjs-static",
    ecosystem: "node",
    framework: "nextjs",
    frameworkVariant: "nextjs-static",
    displayName: "Next.js Static Docker Template",
    description: "Multi-stage Dockerfile for exported static Next.js apps.",
    baseImage: "node:22-alpine3.21",
    runtimeImage: "nginxinc/nginx-unprivileged:1.27-alpine",
    usesMultiStageBuild: true,
    securityLevel: "high",
    defaultPort: 8080,
    requiredFiles: ["package.json"],
    requiredCommands: ["install", "build"],
    outputMode: "static",
    supportedPackageManagers: ["npm", "yarn", "pnpm"],
    dockerfileTemplatePath: "templates/docker/node/nextjs-static.Dockerfile.tpl",
    notes: ["Serves static export with unprivileged nginx on port 8080."],
    warnings: [],
  },
  {
    templateKey: "express-server",
    ecosystem: "node",
    framework: "express",
    frameworkVariant: "express-server",
    displayName: "Express Docker Template",
    description: "Multi-stage Dockerfile for Express apps.",
    baseImage: "node:22-alpine3.21",
    runtimeImage: "node:22-alpine3.21",
    usesMultiStageBuild: true,
    securityLevel: "high",
    defaultPort: 3000,
    requiredFiles: ["package.json"],
    requiredCommands: ["install", "start"],
    outputMode: "server",
    supportedPackageManagers: ["npm", "yarn", "pnpm"],
    dockerfileTemplatePath: "templates/docker/node/express-server.Dockerfile.tpl",
    notes: ["Runs as a non-root user."],
    warnings: [],
  },
  {
    templateKey: "generic-node",
    ecosystem: "node",
    framework: "unknown",
    frameworkVariant: "generic-node",
    displayName: "Generic Node.js Docker Template",
    description: "Multi-stage Dockerfile for generic Node.js apps.",
    baseImage: "node:22-alpine3.21",
    runtimeImage: "node:22-alpine3.21",
    usesMultiStageBuild: true,
    securityLevel: "medium",
    defaultPort: 3000,
    requiredFiles: ["package.json"],
    requiredCommands: ["install", "start"],
    outputMode: "server",
    supportedPackageManagers: ["npm", "yarn", "pnpm"],
    dockerfileTemplatePath: "templates/docker/node/generic-node.Dockerfile.tpl",
    notes: ["Requires a valid start command."],
    warnings: [],
  },
  {
    templateKey: "django-wsgi",
    ecosystem: "python",
    framework: "django",
    frameworkVariant: "django-wsgi",
    displayName: "Django WSGI Docker Template",
    description: "Slim Python Dockerfile for Django WSGI apps.",
    baseImage: "python:3.11-slim",
    runtimeImage: "python:3.11-slim",
    usesMultiStageBuild: true,
    securityLevel: "high",
    defaultPort: 8000,
    requiredFiles: ["requirements.txt"],
    requiredCommands: ["install", "start"],
    outputMode: "server",
    supportedPackageManagers: ["pip", "poetry"],
    dockerfileTemplatePath: "templates/docker/python/django-wsgi.Dockerfile.tpl",
    notes: ["Runs as a non-root user."],
    warnings: [],
  },
  {
    templateKey: "fastapi-asgi",
    ecosystem: "python",
    framework: "fastapi",
    frameworkVariant: "fastapi-asgi",
    displayName: "FastAPI ASGI Docker Template",
    description: "Slim Python Dockerfile for FastAPI apps.",
    baseImage: "python:3.11-slim",
    runtimeImage: "python:3.11-slim",
    usesMultiStageBuild: true,
    securityLevel: "high",
    defaultPort: 8000,
    requiredFiles: ["requirements.txt"],
    requiredCommands: ["install", "start"],
    outputMode: "server",
    supportedPackageManagers: ["pip", "poetry"],
    dockerfileTemplatePath: "templates/docker/python/fastapi-asgi.Dockerfile.tpl",
    notes: ["Runs as a non-root user."],
    warnings: [],
  },
  {
    templateKey: "flask-wsgi",
    ecosystem: "python",
    framework: "flask",
    frameworkVariant: "flask-wsgi",
    displayName: "Flask WSGI Docker Template",
    description: "Slim Python Dockerfile for Flask apps.",
    baseImage: "python:3.11-slim",
    runtimeImage: "python:3.11-slim",
    usesMultiStageBuild: true,
    securityLevel: "high",
    defaultPort: 5000,
    requiredFiles: ["requirements.txt"],
    requiredCommands: ["install", "start"],
    outputMode: "server",
    supportedPackageManagers: ["pip", "poetry"],
    dockerfileTemplatePath: "templates/docker/python/flask-wsgi.Dockerfile.tpl",
    notes: ["Runs as a non-root user."],
    warnings: [],
  },
  {
    templateKey: "generic-python",
    ecosystem: "python",
    framework: "unknown",
    frameworkVariant: "generic-python",
    displayName: "Generic Python Docker Template",
    description: "Slim Python Dockerfile for generic Python apps.",
    baseImage: "python:3.11-slim",
    runtimeImage: "python:3.11-slim",
    usesMultiStageBuild: true,
    securityLevel: "medium",
    defaultPort: 8000,
    requiredFiles: ["requirements.txt"],
    requiredCommands: ["install", "start"],
    outputMode: "server",
    supportedPackageManagers: ["pip", "poetry"],
    dockerfileTemplatePath: "templates/docker/python/generic-python.Dockerfile.tpl",
    notes: ["Requires a valid start command."],
    warnings: [],
  },
  {
    templateKey: "custom-dockerfile",
    ecosystem: "custom",
    framework: "custom",
    frameworkVariant: "custom-dockerfile",
    displayName: "Existing Dockerfile",
    description: "Use the repository-provided Dockerfile.",
    baseImage: "repository-defined",
    runtimeImage: "repository-defined",
    usesMultiStageBuild: false,
    securityLevel: "repository-defined",
    defaultPort: 0,
    requiredFiles: ["Dockerfile"],
    requiredCommands: [],
    outputMode: "custom",
    supportedPackageManagers: [],
    dockerfileTemplatePath: null,
    notes: ["Review the repository Dockerfile before building."],
    warnings: ["Security depends on the repository-provided Dockerfile."],
  },
  {
    templateKey: "custom-dockerfile-required",
    ecosystem: "unknown",
    framework: "unknown",
    frameworkVariant: "custom-dockerfile-required",
    displayName: "Manual Dockerfile Required",
    description: "No safe automatic template is available.",
    baseImage: "none",
    runtimeImage: "none",
    usesMultiStageBuild: false,
    securityLevel: "manual-review-required",
    defaultPort: 0,
    requiredFiles: ["Dockerfile"],
    requiredCommands: [],
    outputMode: "manual",
    supportedPackageManagers: [],
    dockerfileTemplatePath: null,
    notes: ["Provide a custom Dockerfile."],
    warnings: ["No automatic template can be generated safely."],
  },
];
