import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { cleanupSafeOrphans, cleanupSelectedCloudResources, createCentralCleanupChallenge, createEmergencyCleanupChallenge, downloadCloudCleanupReport, executeEmergencyCleanup, getCloudCleanupResources, getCloudCleanupSummary, getEmergencyCleanupOperations, getEmergencyCleanupPreview, markCloudResourcesManualReview, markProjectCleanupComplete, refreshCloudCleanupInventory, retryCentralProjectDestroy } from "../api/adminApi.js";
import { requestDestroy } from "../api/platformApi.js";
import { refreshProjectResources } from "../api/platformApi.js";
import EmptyState from "../components/common/EmptyState.jsx";
import ErrorState from "../components/common/ErrorState.jsx";
import LoadingState from "../components/common/LoadingState.jsx";

const emptyFilters = { projectId: "", resourceType: "", status: "", risk: "", region: "", eligibility: "" };
const labels = { active: "Active", orphan: "Orphan", cleanup_required: "Cleanup required", protected: "Protected", deleted: "Deleted", manual_review: "Manual review" };
const inventoryTabs = ["all", "high_cost", "safe", "manual", "protected", "errors", "deleted"];

export default function AdminCloudCleanup() {
  const [dashboard, setDashboard] = useState(null);
  const [resources, setResources] = useState([]);
  const [resourceGroups, setResourceGroups] = useState([]);
  const [emergencyPreview, setEmergencyPreview] = useState(null);
  const [emergencyOperations, setEmergencyOperations] = useState([]);
  const [emergencyConfirmation, setEmergencyConfirmation] = useState(null);
  const [emergencyPhrase, setEmergencyPhrase] = useState("");
  const [filters, setFilters] = useState(emptyFilters);
  const [selected, setSelected] = useState([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [authUnavailable, setAuthUnavailable] = useState(false);
  const [notice, setNotice] = useState("");
  const [confirmation, setConfirmation] = useState(null);
  const [phrase, setPhrase] = useState("");
  const [destroyConfirmation, setDestroyConfirmation] = useState(null);
  const [destroyPhrase, setDestroyPhrase] = useState("");
  const [activeTab, setActiveTab] = useState("all");

  async function load(nextFilters = filters) {
    setError(""); setLoading(true);
    try { const [summary, inventory, emergency, operations] = await Promise.all([getCloudCleanupSummary(), getCloudCleanupResources(nextFilters), getEmergencyCleanupPreview(), getEmergencyCleanupOperations()]); setDashboard(summary); setResources(inventory.resources || []); setResourceGroups(inventory.groups || []); setEmergencyPreview(emergency); setEmergencyOperations(operations || []); setSelected([]); setAuthUnavailable(false); }
    catch (caught) { if ([401, 403].includes(caught.status)) { setAuthUnavailable(true); setError(""); } else setError(caught.message); }
    finally { setLoading(false); }
  }
  useEffect(() => { void load(emptyFilters); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(filters), 180); return () => window.clearTimeout(timer); }, [filters.projectId, filters.resourceType, filters.status, filters.risk, filters.region, filters.eligibility]);
  useEffect(() => {
    if (!emergencyOperations.some((operation) => ["queued", "running", "waiting_for_project_cleanup"].includes(operation.status))) return undefined;
    const timer = window.setInterval(() => getEmergencyCleanupOperations().then(setEmergencyOperations).catch(() => undefined), 4000);
    return () => window.clearInterval(timer);
  }, [emergencyOperations]);

  const safeSelected = useMemo(() => resources.filter((resource) => selected.includes(resource.id) && resource.safeToCleanup && !resource.protected), [resources, selected]);
  const manualResources = resources.filter((resource) => resource.status === "manual_review");
  const summary = dashboard?.summary || {};

  async function refresh() { setBusy("refresh"); setError(""); setNotice(""); try { const response = await refreshCloudCleanupInventory(); setNotice(response.warnings?.length ? `Inventory completed with ${response.warnings.length} warning(s). Unverified resources remain protected.` : "Cloud inventory refreshed."); await load(filters); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function beginCleanup(action) { setBusy(action); setError(""); try { setConfirmation({ action, challenge: await createCentralCleanupChallenge(action) }); setPhrase(""); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function executeCleanup() { if (!confirmation || phrase !== confirmation.challenge.confirmationPhrase) return; setBusy("cleanup"); setError(""); try { const body = { challengeId: confirmation.challenge.challengeId, challengeToken: confirmation.challenge.challengeToken, confirmationPhrase: phrase, ...(confirmation.action === "selected" ? { resourceIds: safeSelected.map((resource) => resource.id) } : {}) }; const response = confirmation.action === "selected" ? await cleanupSelectedCloudResources(body) : await cleanupSafeOrphans(body); const failed = response.results?.filter((result) => result.status === "failed").length || 0; setNotice(failed ? `Cleanup completed with ${failed} failure(s). Review the resource table.` : "Cleanup completed and inventory was refreshed."); setConfirmation(null); setPhrase(""); await load(filters); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function markManual() { if (!selected.length) return; setBusy("manual"); setError(""); try { await markCloudResourcesManualReview(selected); setNotice("Selected resources marked for manual review."); await load(filters); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function exportReport() { setBusy("export"); setError(""); try { await downloadCloudCleanupReport(); setNotice("Sanitized cleanup report exported."); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function prepareRetry(project) { setBusy(`retry-${project.id}`); setError(""); try { const challenge = await retryCentralProjectDestroy(project.id, project.latestDestroy.id); setDestroyConfirmation({ project, challenge }); setDestroyPhrase(""); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function refreshProject(project) { setBusy(`scan-${project.id}`); setError(""); try { const result = await refreshProjectResources(project.id); setNotice(result.scan?.errors?.length ? `${project.name} scan completed with errors.` : `${project.name} inventory refreshed.`); await load(filters); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function completeProject(project) { setBusy(`complete-${project.id}`); setError(""); try { await markProjectCleanupComplete(project.id); setNotice(`${project.name} cleanup marked complete from verified inventory.`); await load(filters); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function executeRetry() { if (!destroyConfirmation || destroyPhrase !== "DESTROY") return; setBusy("retry-destroy"); setError(""); try { const { project, challenge } = destroyConfirmation; await requestDestroy(project.id, { challengeId: challenge.challengeId, challengeToken: challenge.challengeToken, confirmationPhrase: destroyPhrase, environmentName: challenge.environmentName || project.latestDestroy.environmentName || "dev" }); setNotice(`Terraform destroy retry queued for ${project.name}.`); setDestroyConfirmation(null); setDestroyPhrase(""); await load(filters); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function beginEmergency() { setBusy("emergency-challenge"); setError(""); try { setEmergencyConfirmation(await createEmergencyCleanupChallenge()); setEmergencyPhrase(""); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  async function runEmergency() { if (!emergencyConfirmation || emergencyPhrase !== "DESTROY ALL DEPLOYGUARD TEST RESOURCES") return; setBusy("emergency"); setError(""); try { await executeEmergencyCleanup({ challengeId: emergencyConfirmation.challengeId, challengeToken: emergencyConfirmation.challengeToken, confirmationPhrase: emergencyPhrase }); setEmergencyConfirmation(null); setEmergencyPhrase(""); setNotice("Emergency non-production cleanup queued. Project Terraform destroys will run before verified direct residue cleanup."); await load(filters); } catch (caught) { setError(caught.message); } finally { setBusy(""); } }
  function toggle(id) { setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); }

  return <div className="grid central-cleanup-page">
    <header className="page-header central-cleanup-header"><div><p className="eyebrow">Admin operations</p><h1>Resource Command Center</h1><p className="muted">Project-aware cleanup, cost-risk triage, TTL status, and protected AWS inventory in {summary.region || "the configured region"}.</p></div><div className="quick-actions"><button className="subtle-button" disabled={Boolean(busy)} onClick={exportReport} type="button">Export report</button><button className="secondary-button" disabled={Boolean(busy)} onClick={refresh} type="button">{busy === "refresh" ? "Scanning AWS…" : "Refresh inventory"}</button></div></header>
    <div className="state warning protected-cloud-notice"><strong>Protected by default</strong><span>This tool only cleans DeployGuard-scoped cloud resources. Shared platform resources such as the Terraform state bucket are protected.</span></div>
    {error ? <ErrorState message={error} /> : null}{notice ? <p className="state success">{notice}</p> : null}
    {authUnavailable ? <section className="panel-flat inventory-auth-unavailable" role="alert"><p className="eyebrow">Inventory unavailable</p><h2>Authentication required</h2><p>Your cloud inventory could not be loaded. No zero counts or clean-state conclusions are being shown.</p><div className="quick-actions"><Link className="button" to="/login">Login again</Link><button className="secondary-button" onClick={() => void load(filters)} type="button">Refresh session</button></div></section> : null}
    {!authUnavailable ? <>
    <section className="cleanup-summary-grid" aria-label="Cloud resource summary">
      <Summary label="Active projects" value={summary.activeProjects} />
      <Summary label="Active cloud resources" value={summary.activeProjectResources} />
      <Summary label="Cleanup required projects" value={summary.cleanupRequiredProjects} tone="danger" />
      <Summary label="High cost-risk resources" value={summary.highCostRiskResources} tone="danger" />
      <Summary label="Protected resources" value={summary.protectedSharedResources} />
      <Summary label="Manual review" value={summary.manualReviewResources} tone="warning" />
      <Summary label="Inventory errors" value={summary.inventoryErrors} tone={summary.inventoryErrors ? "danger" : "neutral"} />
    </section>
    <section className="cleanup-command-panels">
      <article className="panel-flat"><p className="eyebrow">Cost risk</p><h2>{summary.highCostRiskResources || 0} resources need cost attention</h2><p>NAT gateways, ALBs, ECS services/tasks, EIPs, EFS, and large log groups are prioritized without inventing cost estimates.</p><button className="secondary-button" onClick={() => { setActiveTab("high_cost"); setFilters({ ...filters, risk: "high", status: "" }); }} type="button">Resolve cost risks</button></article>
      <article className="panel-flat emergency-control"><p className="eyebrow">Emergency controls</p><h2>Destroy testing and preview resources</h2><p>{emergencyPreview?.targetCount || 0} eligible project environment(s), {emergencyPreview?.resourceCount || 0} tagged resources. Production and shared resources are structurally excluded.</p><button className="danger-button" disabled={Boolean(busy) || !emergencyPreview?.targetCount} onClick={beginEmergency} type="button">Destroy all DeployGuard testing/preview resources</button></article>
      <article className="panel-flat"><p className="eyebrow">Cleanup operations</p><h2>Recent jobs</h2><ul className="command-operation-list">{(dashboard?.cleanupOperations || []).slice(0, 5).map((operation) => <li key={`${operation.kind}-${operation.id}`}><span>{human(operation.kind)}</span><strong>{human(operation.cleanupStatus || operation.status)}</strong></li>)}</ul>{emergencyOperations[0] ? <details><summary>Latest emergency progress</summary><ul className="command-operation-list">{emergencyOperations[0].targets.map((target) => <li key={target.projectId}><span>{target.projectName}</span><strong>{human(target.status)}</strong></li>)}</ul></details> : null}{!dashboard?.cleanupOperations?.length ? <p className="muted">No cleanup operations have been recorded.</p> : null}</article>
      <article className="panel-flat"><p className="eyebrow">Inventory health</p><h2>{human(dashboard?.latestScan?.status || "not scanned")}</h2><p>{dashboard?.latestScan ? `${dashboard.latestScan.servicesChecked.length} services checked · ${dashboard.latestScan.errors.length} errors` : "Run an inventory refresh to establish verified cloud state."}</p></article>
    </section>
    {summary.highCostRiskResources ? <div className="high-cost-warning"><div><p className="eyebrow">Cost attention</p><strong>{summary.highCostRiskResources} active resource{summary.highCostRiskResources === 1 ? "" : "s"} may carry high ongoing cost</strong><span>NAT gateways, load balancers, running ECS services/tasks, and EFS are prioritized for review. Cost is risk-classified; no fabricated price estimate is shown.</span></div><button className="secondary-button" onClick={() => { setActiveTab("high_cost"); setFilters({ ...filters, risk: "high", status: "" }); }} type="button">Review high-cost resources</button></div> : null}
    {dashboard?.latestScan ? <section className="scan-evidence-bar"><div><span>Latest account scan</span><strong>{human(dashboard.latestScan.status)}</strong></div><div><span>Services checked</span><strong>{dashboard.latestScan.servicesChecked.length}</strong></div><div><span>Resources observed</span><strong>{dashboard.latestScan.resourceCount}</strong></div><div><span>Completed</span><strong>{formatDate(dashboard.latestScan.completedAt)}</strong></div></section> : <div className="state warning">No completed account-wide AWS inventory scan exists. Refresh inventory before drawing cleanup conclusions.</div>}
    {dashboard?.latestScan?.errors?.length ? <section className="panel-flat inventory-errors-panel"><div><p className="eyebrow">Inventory errors</p><h2>Some AWS services could not be verified</h2><p>Resources in unverified services remain protected from automatic cleanup.</p></div><ul>{dashboard.latestScan.errors.map((item) => <li key={item}>{item}</li>)}</ul></section> : null}
    {loading && !dashboard ? <LoadingState message="Loading cloud cleanup inventory…" /> : null}
    <section className="panel-flat central-project-status">
      <div className="compact-section-heading"><div><p className="eyebrow">Projects</p><h2>Project cleanup status</h2><p>Infrastructure state and verified AWS residue are kept separate.</p></div></div>
      <div className="cloud-inventory-table"><table><thead><tr><th>Project</th><th>Deployment</th><th>Health</th><th>Infrastructure</th><th>Resources</th><th>Cleanup</th><th>Next action</th><th>Actions</th></tr></thead><tbody>{(dashboard?.projects || []).map((project) => <tr key={project.id}><td><strong>{project.name}</strong><small>{project.repositoryFullName || project.id}</small></td><td>{human(project.deploymentStatus)}<small>{human(project.cloudVerificationStatus)}</small></td><td>{human(project.healthStatus)}</td><td>{human(project.infrastructureStatus)}</td><td>{human(project.resourceStatus)}<small>{project.resourceCount} found · {project.highCostCount} high cost</small></td><td>{human(project.cleanupStatus)}<small>{project.manualReviewCount} manual review</small></td><td>{human(project.nextAction)}<small>{project.statusExplanation}</small></td><td><div className="table-actions"><button className="table-link" onClick={() => setFilters({ ...emptyFilters, projectId: project.id })} type="button">View resources</button><Link className="subtle-button" to={`/projects/${project.id}/settings`}>Open settings</Link><button className="subtle-button" disabled={Boolean(busy)} onClick={() => refreshProject(project)} type="button">{busy === `scan-${project.id}` ? "Scanning…" : "Refresh"}</button>{project.latestDestroy?.status === "failed" ? <button className="subtle-button" disabled={Boolean(busy)} onClick={() => prepareRetry(project)} type="button">Retry destroy</button> : null}{project.canMarkCleanupComplete ? <button className="subtle-button" disabled={Boolean(busy)} onClick={() => completeProject(project)} type="button">Mark complete</button> : null}</div></td></tr>)}</tbody></table></div>
      {!dashboard?.projects?.length ? <EmptyState message="No projects found." /> : null}
    </section>
    <section className="panel-flat central-resource-inventory"><div className="compact-section-heading"><div><p className="eyebrow">Grouped AWS inventory</p><h2>Resources by project and cleanup path</h2><p>Terraform dependencies are one stack; ECR images and policies stay nested under their repository.</p></div><div className="quick-actions"><button className="danger-button" disabled={!safeSelected.length || Boolean(busy)} onClick={() => beginCleanup("selected")} type="button">Clean selected safe resources</button><button className="danger-text-button" disabled={!summary.safeOrphanResources || Boolean(busy)} onClick={() => beginCleanup("safe_orphans")} type="button">Clean all safe orphans</button></div></div>
      <div className="cleanup-project-groups">{resourceGroups.map((group) => <details key={group.projectId || "unmapped"}><summary><span><strong>{group.projectName}</strong><small>{group.projectId || "Ownership not mapped"}</small></span><span>{group.terraformStack.length} Terraform · {group.directCleanup.ecrRepositories.length + group.directCleanup.logs.length + group.directCleanup.secrets.length + group.directCleanup.oldTaskDefinitions.length} direct · {group.manualReview.length} manual · {group.protected.length} protected</span></summary><div className="cleanup-path-grid"><CleanupPath title="Terraform stack" items={group.terraformStack} /><CleanupPath title="Direct cleanup" items={[...group.directCleanup.ecrRepositories, ...group.directCleanup.logs, ...group.directCleanup.secrets, ...group.directCleanup.oldTaskDefinitions]} /><CleanupPath title="Protected" items={group.protected} /><CleanupPath title="Manual review" items={group.manualReview} /></div></details>)}</div>
      <details className="raw-resource-details"><summary>Open individual resource inventory and filters</summary>
      <div className="cleanup-tabs" role="tablist">{inventoryTabs.map((value) => <button aria-selected={activeTab === value} className={activeTab === value ? "active" : ""} key={value} onClick={() => { setActiveTab(value); if (value === "all") setFilters({ ...filters, status: "", risk: "", eligibility: "" }); if (value === "high_cost") setFilters({ ...filters, status: "", risk: "high", eligibility: "" }); if (value === "safe") setFilters({ ...filters, status: "", risk: "", eligibility: "safe" }); if (value === "manual") setFilters({ ...filters, status: "", risk: "", eligibility: "manual" }); if (value === "protected") setFilters({ ...filters, status: "", risk: "", eligibility: "protected" }); if (value === "deleted") setFilters({ ...filters, status: "deleted", risk: "", eligibility: "" }); }} role="tab" type="button">{human(value)}</button>)}</div>
      {activeTab !== "errors" ? <><div className="cleanup-filters"><select aria-label="Project filter" onChange={(event) => setFilters({ ...filters, projectId: event.target.value })} value={filters.projectId}><option value="">All projects</option>{(dashboard?.projects || []).map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><select aria-label="Resource type filter" onChange={(event) => setFilters({ ...filters, resourceType: event.target.value })} value={filters.resourceType}><option value="">All resource types</option>{unique(resources.map((resource) => resource.type)).map((value) => <option key={value} value={value}>{human(value)}</option>)}</select><select aria-label="Status filter" onChange={(event) => setFilters({ ...filters, status: event.target.value })} value={filters.status}><option value="">All statuses</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Risk filter" onChange={(event) => setFilters({ ...filters, risk: event.target.value })} value={filters.risk}><option value="">All risk levels</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option><option value="none">None</option></select><select aria-label="Region filter" onChange={(event) => setFilters({ ...filters, region: event.target.value })} value={filters.region}><option value="">All regions</option>{unique(resources.map((resource) => resource.region)).map((value) => <option key={value} value={value}>{value}</option>)}</select><select aria-label="Cleanup eligibility filter" onChange={(event) => setFilters({ ...filters, eligibility: event.target.value })} value={filters.eligibility}><option value="">All eligibility</option><option value="safe">Safe cleanup</option><option value="manual">Manual review</option><option value="protected">Protected</option></select></div>
      <div className="cloud-inventory-table central-resource-table"><table><thead><tr><th>Select</th><th>Resource</th><th>Type / service</th><th>Region</th><th>Project</th><th>Run</th><th>Ownership</th><th>Cleanup path</th><th>Status</th><th>Cost risk</th><th>First / last seen</th><th>Actions</th></tr></thead><tbody>{resources.map((resource) => <tr key={resource.id} className={resource.costRisk === "high" ? "high-cost-row" : ""}><td><input aria-label={`Select ${resource.name}`} checked={selected.includes(resource.id)} disabled={!resource.safeToCleanup || resource.protected || resource.status === "deleted"} onChange={() => toggle(resource.id)} type="checkbox" /></td><td><strong>{resource.name}</strong><small>{resource.reason}</small></td><td>{human(resource.type)}<small>{resource.awsService}</small></td><td>{resource.region}</td><td>{resource.projectName || (resource.projectId ? "Known project" : "Unmapped")}<small>{resource.projectId || "—"}</small></td><td>{resource.pipelineRunId ? resource.pipelineRunId.slice(0, 8) : "—"}</td><td>{human(resource.ownership)}</td><td>{human(resource.cleanupEligibility)}</td><td><span className={`cleanup-status ${resource.status}`}>{labels[resource.status] || human(resource.status)}</span></td><td><span className={`cost-risk ${resource.costRisk}`}>{resource.costRisk}</span></td><td><small>{formatDate(resource.firstSeen)}</small>{formatDate(resource.lastSeen)}</td><td>{resource.projectId ? <Link className="table-link" to={`/projects/${resource.projectId}/settings`}>Open cleanup</Link> : "—"}</td></tr>)}</tbody></table></div></> : dashboard?.latestScan?.errors?.length ? <ul className="inventory-error-list">{dashboard.latestScan.errors.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="resource-empty-copy">The latest account scan recorded no inventory errors.</p>}
      {!loading && !resources.length ? <EmptyState message="No resources match these filters. Refresh inventory to scan AWS." /> : null}
      <div className="quick-actions cleanup-selection-actions"><span>{selected.length} selected · {safeSelected.length} safe to clean</span><button className="subtle-button" disabled={!selected.length || Boolean(busy)} onClick={markManual} type="button">Mark as manual review</button></div></details>
    </section>
    <section className="panel-flat manual-review-panel"><div><p className="eyebrow">Manual review</p><h2>Resources requiring administrator review</h2><p>Uncertain ALB, VPC, NAT, EIP, EFS, IAM, and network resources are never automatically deleted.</p></div>{manualResources.length ? <ul>{manualResources.slice(0, 12).map((resource) => <li key={resource.id}><strong>{resource.name}</strong><span>{human(resource.type)} · {resource.reason}</span></li>)}</ul> : <p className="muted">No resources in the current view require manual review.</p>}</section>
    </> : null}
    {confirmation ? <ConfirmModal busy={busy === "cleanup"} challenge={confirmation.challenge} onCancel={() => setConfirmation(null)} onConfirm={executeCleanup} phrase={phrase} setPhrase={setPhrase} /> : null}
    {destroyConfirmation ? <div className="destroy-modal-backdrop"><section aria-modal="true" className="destroy-modal" role="dialog"><p className="eyebrow">Terraform destroy retry</p><h2>Retry destroy for {destroyConfirmation.project.name}?</h2><p>The project state scope and shared bucket protections remain active.</p><label className="field"><span>Type <strong>DESTROY</strong> to confirm</span><input autoFocus onChange={(event) => setDestroyPhrase(event.target.value)} value={destroyPhrase} /></label><div className="destroy-modal-actions"><button className="subtle-button" disabled={Boolean(busy)} onClick={() => setDestroyConfirmation(null)} type="button">Cancel</button><button className="danger-button" disabled={Boolean(busy) || destroyPhrase !== "DESTROY"} onClick={executeRetry} type="button">Retry Terraform destroy</button></div></section></div> : null}
    {emergencyConfirmation ? <div className="destroy-modal-backdrop"><section aria-modal="true" className="destroy-modal emergency-modal" role="dialog"><p className="eyebrow">Non-production panic mode</p><h2>Destroy all eligible testing resources?</h2><p>This enqueues project-scoped Terraform destroy first, then safe tagged residues. Production, shared resources, state files, backups, and the state bucket are excluded.</p><label className="field"><span>Type <strong>DESTROY ALL DEPLOYGUARD TEST RESOURCES</strong></span><input autoFocus autoComplete="off" onChange={(event) => setEmergencyPhrase(event.target.value)} value={emergencyPhrase} /></label><div className="destroy-modal-actions"><button className="subtle-button" disabled={Boolean(busy)} onClick={() => setEmergencyConfirmation(null)} type="button">Cancel</button><button className="danger-button" disabled={Boolean(busy) || emergencyPhrase !== "DESTROY ALL DEPLOYGUARD TEST RESOURCES"} onClick={runEmergency} type="button">{busy === "emergency" ? "Queueing…" : "Queue emergency cleanup"}</button></div></section></div> : null}
  </div>;
}

function Summary({ label, value, tone = "neutral" }) { return <article className={`cleanup-summary-card ${tone}`}><span>{label}</span><strong>{value ?? 0}</strong></article>; }
function CleanupPath({ title, items }) { return <article><span>{title}</span><strong>{items.length}</strong>{items.length ? <ul>{items.slice(0, 5).map((item) => <li key={item.id}>{item.name}{item.children?.length ? ` (+${item.children.length} included)` : ""}</li>)}</ul> : <small>None</small>}</article>; }
function ConfirmModal({ challenge, phrase, setPhrase, onCancel, onConfirm, busy }) { return <div className="destroy-modal-backdrop"><section aria-modal="true" className="destroy-modal" role="dialog"><p className="eyebrow">Admin-only destructive action</p><h2>Confirm cloud cleanup</h2><p>Only currently verified, DeployGuard-scoped resources with supported cleanup operations will be targeted. Shared platform resources remain protected.</p><label className="field"><span>Type <strong>{challenge.confirmationPhrase}</strong> to confirm</span><input autoFocus autoComplete="off" onChange={(event) => setPhrase(event.target.value)} value={phrase} /></label><div className="destroy-modal-actions"><button className="subtle-button" disabled={busy} onClick={onCancel} type="button">Cancel</button><button className="danger-button" disabled={busy || phrase !== challenge.confirmationPhrase} onClick={onConfirm} type="button">{busy ? "Cleaning…" : "Confirm cleanup"}</button></div></section></div>; }
function unique(values) { return [...new Set(values.filter(Boolean))].sort(); }
function human(value) { return String(value || "—").replaceAll("_", " "); }
function formatDate(value) { return value ? new Date(value).toLocaleString() : "—"; }
